api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "d164aba5982a8d169d251acdfeedae89a2aa19de4096f074a4fbcb588203725d"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.22.tar.gz"
source_sha256 = "fda517e74d29d0f85178264f40d488b35f16d2d4c0ef1d77d0ce2078039e47b0"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.22-any-stack-d164aba5.tgz"
version = "0.0.22"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "238ac28199ea1de73dd5b70a72eb9c6ee8093b0b677aa742520c594b287a9a61"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.32.tar.gz"
source_sha256 = "347b5113017a2e17e8bf580e6f09ddc87386c405fa23675bd1322fa3683f85a7"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.32-any-stack-238ac281.tgz"
version = "0.0.32"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "62bb81b7f627b67154895363ebaa7143ab1fad60f729fb0d36c8a14557f4525c"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.20.tar.gz"
source_sha256 = "058c9f6f9099b9c50fc82b2b80fd4942cb1dfd0fdb2a976ff88e3e9585d6e61e"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.20-any-stack-62bb81b7.tgz"
version = "0.0.20"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "b0b34256f154c88215309cedecfd81cdb75165d88ecb2733f6038d11ee1aa344"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.32.tar.gz"
source_sha256 = "da827c9fc7addb1fcbed8f86d64fe9a0d285aa5086a93c7eaf3c764ad1130573"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.32-any-stack-b0b34256.tgz"
version = "0.0.32"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.32"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.20"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.32"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.22"
