api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "cc81959211f461cb7c2c041a4752b262bd02bfb99c346c08ffa1c9f2c9d1e8cf"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.53.tar.gz"
    source_sha256 = "d55fb1df6f934a5888211704807403cb1ed9cdfb59d3ef89ac0cf6ce9143738b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.53-any-stack-cc819592.tgz"
    version = "0.0.53"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "1a9a3ace3e83ab085737f63812723b41568431ad5c7bd4b2320519ed3788cdb6"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.75.tar.gz"
    source_sha256 = "47bd8e9cbf3756069eec78bd3d331dfffdd090cee23dff3311abe4aa6d527757"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.75-any-stack-1a9a3ace.tgz"
    version = "0.0.75"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "a6880ed2a26bf8fdb5ae2381a0bfd56f2e3d7af39d69625d113398a04d02b0dd"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.61.tar.gz"
    source_sha256 = "a03e24c8d4132bf00965d8285ce2fd1b8b2fef544ad1801e57481b88112f2ed2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.61-any-stack-a6880ed2.tgz"
    version = "0.0.61"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "999265f3736a31affd2f00523a4facc699ef6b5e95d4168721269af6acbef07b"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.79.tar.gz"
    source_sha256 = "ca4d03b02c05f7440a1d16474655ce3ca43b377ec4ce266704377e3cf76ffe48"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.79-any-stack-999265f3.tgz"
    version = "0.0.79"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.79"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.61"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.75"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.53"
