api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "61fd9710045d1745923113b60d4f6936b3a0da7a6886c1959b6d7a16f6538893"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.74.tar.gz"
    source_sha256 = "8aa45049c6fcc04e1486edbbc951877139e65a640757366dc224c520a5136a51"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.74-any-stack-61fd9710.tgz"
    version = "0.0.74"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "57aa01c496f65dbeb1e4a75b486636eaaf99b2380b44d55745f9a79ad62244a9"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.97.tar.gz"
    source_sha256 = "e985587478acb0f65afdf75649d266f3c8f22edd419de8edff281fd6a5a81dca"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.97-any-stack-57aa01c4.tgz"
    version = "0.0.97"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "d9b7dccf40a5288ed7af69a27ce8420df73e8655bcf1e38889a6874c2762072d"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.79.tar.gz"
    source_sha256 = "97d59eb79a726f7f4ecfaea9bbd1924cf174d1cdc32c59d7431806df2c909e80"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.79-cflinuxfs3-d9b7dccf.tgz"
    version = "0.0.79"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "56c05e95ba3f83df45c6990d546b757423adc087b59bc686528a053c2b54f06f"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.100.tar.gz"
    source_sha256 = "a539bf1b64c6434f2e14a1aaab4c749e0df685bc6a0942a13eeb51af114aab74"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.100-cflinuxfs3-56c05e95.tgz"
    version = "0.0.100"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.100"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.79"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.97"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.74"
