api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "44369e3fd1cbdafce2796e8b95970405029df3178317615ad7b2dbce0f7543d6"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.50.tar.gz"
    source_sha256 = "0f471705abe3f67bda7562011b151509fe6aa7515666d84ef538c4c8594aea6a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.50-any-stack-44369e3f.tgz"
    version = "0.0.50"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "7c9fe0329db42dc2801a31ce7460b6f95b5ede80b0887c30ee669899ed58e0f2"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.70.tar.gz"
    source_sha256 = "d9bdfcca82ae215995ce051c12a7c0845e2e196b20f940a6a298c7785ea3b874"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.70-any-stack-7c9fe032.tgz"
    version = "0.0.70"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "665ab26ef09f101b4ccc8fd0ae7eb299ae9bba3f3940ab138d6eefe11c9072ed"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.57.tar.gz"
    source_sha256 = "f0341856d24dc2289f23ebcace6a45ff3e8069308240f4101abe46c0fb41d78f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.57-any-stack-665ab26e.tgz"
    version = "0.0.57"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "e59af80f9f8c0ccadebb03ca53dbe0682c7dd37a047e1334d2176545c1bcc43e"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.71.tar.gz"
    source_sha256 = "c104f3389f34e86a0a2a73d57d2ba6fef29592addf9c5635eea5d9a289b9ca56"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.71-any-stack-e59af80f.tgz"
    version = "0.0.71"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.71"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.57"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.70"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.50"
