api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "8dad1a6c9e9b4fa56b7d8c20b46d154dab4df921383ea60c9b23c9c2b047b8df"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.35.tar.gz"
source_sha256 = "24b141493cbcb548d00713b4909b1f80e40eceaca0c26c0a53467aab44efcefc"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.35-any-stack-8dad1a6c.tgz"
version = "0.0.35"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "4223546d2a4861805ad6ff8c9b74ab91bb7885985110212271d8c77aeda2e606"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.46.tar.gz"
source_sha256 = "a6c2344b6708c42005a607f89e8421eae3fbf8601f913fac9972c678295776b7"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.46-any-stack-4223546d.tgz"
version = "0.0.46"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "31c9f0a2fc209a305e62b84eeeac457dcdaf08e2b7bc8f11e8d6117d90a4ab3e"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.32.tar.gz"
source_sha256 = "84b3290a0b8febac2fa59d4156e2d7c509719505bc15b4d2cf31a6af5df33901"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.32-any-stack-31c9f0a2.tgz"
version = "0.0.32"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "5808292c36058f775ff73929ca2119e2eecd04c9be41cd533d08b3fa66af1ad0"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.47.tar.gz"
source_sha256 = "63d1ea26e610be34c297ba7a71bae206c2d58d55e6e1bb1ae0a9f0664f938095"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.47-any-stack-5808292c.tgz"
version = "0.0.47"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.47"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.32"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.46"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.35"
