api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "6895e4bd19fbd1ee4cd49d0637e2ef038d03e749132b54ba00a85eb766a817ac"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.43.tar.gz"
    source_sha256 = "880e1270952d2bb0eceaba42951471edc7c0c72f17ad4f238d3c4d16d425418d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.43-any-stack-6895e4bd.tgz"
    version = "0.0.43"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "10db078debb44c57fd137343cbc3d03d289a4a4042d9aa1edbc20ff3e4121856"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.62.tar.gz"
    source_sha256 = "960caac14d7832f1ec3df1c982596ed497874b4d191be2152f3407007a556230"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.62-any-stack-10db078d.tgz"
    version = "0.0.62"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "a66dacffc5b833e6adfbe4e0dd51fff7d16cf31e46ae7b9b382e03da4f58c07e"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.49.tar.gz"
    source_sha256 = "086c780685f2961d17f859b38414f1123a0fcc7b05fd010c36aa33405813a88e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.49-any-stack-a66dacff.tgz"
    version = "0.0.49"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "ce123fb12eec41c673cce6ee239a2d360a2f8fd9ae178bf747cc8452853cf5b9"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.63.tar.gz"
    source_sha256 = "2e620e1cffd350a0cdd47083b01229418994fc45a9c3b8ffa43a47487da8dd2e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.63-any-stack-ce123fb1.tgz"
    version = "0.0.63"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.63"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.49"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.62"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.43"
