api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "6281d187d54a3f2d45646ef65a18daf5193f941993968ccd543235a0538a01e0"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.34.tar.gz"
source_sha256 = "fd9caebabb43a99fd044c9f8a5c5a998f914ebcfbcc8d949130d80fd404295a4"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.34-any-stack-6281d187.tgz"
version = "0.0.34"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "553e8285c0b32e02ae5645cad11da29614267b39f8a7bc75fffe56759495717d"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.45.tar.gz"
source_sha256 = "45d136df463d69e04235ff557647927904a0cd4b7d9e7e1be358e9891485a164"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.45-any-stack-553e8285.tgz"
version = "0.0.45"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "2fccdfe7a4696dc466ef524f91ea6e93afa1734fb4b0c608c845e1af60d7d2b5"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.31.tar.gz"
source_sha256 = "d80efb4cb58137f99ba89040c277265aa14c97e6f6ac51685c274643a23ca673"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.31-any-stack-2fccdfe7.tgz"
version = "0.0.31"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "86cf2079690d0ad30566cf6dd6e179298df08a7503daea3f382110f88e97fb42"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.44.tar.gz"
source_sha256 = "a5ead4f8c969391c47d3ec4287b0b57031b6ee8742f2ac179c1cca63b7bb6d40"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.44-any-stack-86cf2079.tgz"
version = "0.0.44"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.44"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.31"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.45"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.34"
