api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "7f2fed9e349684db3cfb0e11c09099e2e5986822356575b5cb476ad8c8fe7431"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.63.tar.gz"
    source_sha256 = "4b19459c33a911398f6e256a36e5b191dc5dce7441a4a68f8bab79a8278aa084"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.63-any-stack-7f2fed9e.tgz"
    version = "0.0.63"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "507d266ccd63b0b46a12ab35f790e9ec220e9f143be8fff6c5184c20b015ef8f"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.85.tar.gz"
    source_sha256 = "63c361ca8e15e9f7ec644a2a5949b56517317dccf79de0ecf8b4bb06ca0d535d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.85-any-stack-507d266c.tgz"
    version = "0.0.85"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "fbe0a444d157228a78a0b7b99048dccbfa4770429f6d02d20b1573112512803f"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.70.tar.gz"
    source_sha256 = "21627b1ef210c0779b8aae764f6522ea3b186bd646101a26dbdfbe801fd30750"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.70-any-stack-fbe0a444.tgz"
    version = "0.0.70"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "969cc3962c998f881a97f660a8b699c252e990ada8462c89d0a8551361032fef"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.88.tar.gz"
    source_sha256 = "3544bc269f96cd8d41202f9687186050f686969f3522a17546f3b1a48f1a3ab8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.88-any-stack-969cc396.tgz"
    version = "0.0.88"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.88"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.70"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.85"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.63"
