api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "99b9f67101ef3195fb78c5da51e73ed0e80a26ace6059eadbf95fdc683298d57"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.27.tar.gz"
source_sha256 = "32fb411b5526605157802a0b4236c8d20073e568a263c5ca57d11f84de5162da"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.27-any-stack-99b9f671.tgz"
version = "0.0.27"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "7aa9deabf0112bab85dcd3d44c2f8e600ccccc934686c583f1ac28c1e5445f94"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.38.tar.gz"
source_sha256 = "2a432ee3b5a1250a4d2200181097efee5a0c37387b68a8d919138e60db7ef278"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.38-any-stack-7aa9deab.tgz"
version = "0.0.38"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "8d55b5cc5e512b199e6ce281bfb429335a402268d6bf9a45364dc7a6d39fd203"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.26.tar.gz"
source_sha256 = "4fd97c53d480a2066e5414371ea18ba485e8b5cc80062f25189a6241eb75a1a6"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.26-any-stack-8d55b5cc.tgz"
version = "0.0.26"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "19f68aabce6f4149b00b19301db016a957508b953ef0d973f1f2be5962468809"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.37.tar.gz"
source_sha256 = "0e79e861a1881a5b1a193ca4e5bcad12551ec29359d040f221e868dfa66e2532"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.37-any-stack-19f68aab.tgz"
version = "0.0.37"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.37"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.26"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.38"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.27"
