api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "5990d4d79a01d6a8d3f71ebfba5bf4b16a7b07e3392ab8f46be6ba3969290046"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.57.tar.gz"
    source_sha256 = "5da3dd16c045a2c008d4b3455a0d38b661dfecab1784527cbcc435d92557109e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.57-any-stack-5990d4d7.tgz"
    version = "0.0.57"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "41063e751fad8cfa46c476f8e05c27301cdb13e9abbfc26132293cf273ba6355"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.81.tar.gz"
    source_sha256 = "52216db94ce1496a5e3cd8dfe320e0ea33144dfaa1bf6038c2547de49b4a987a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.81-any-stack-41063e75.tgz"
    version = "0.0.81"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "22de9e0741e0af03019aaf6a9d50a23f41f1eb251e6b0ddfca19f6cf3873b783"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.64.tar.gz"
    source_sha256 = "dbcd472cbfdffb81a397980e25c9cd9c88c644b93fe9f9d000d2fa0c3dee0669"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.64-any-stack-22de9e07.tgz"
    version = "0.0.64"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "40227ff62245bdbc5cf0f2e08190889bcc98cb53321245ebf155cf6191238328"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.83.tar.gz"
    source_sha256 = "a3e1f8efb2a5603045deb1688f518b6227265dc5bdce0f31e9d034692d34700d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.83-any-stack-40227ff6.tgz"
    version = "0.0.83"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.83"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.64"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.81"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.57"
