api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "9e5cb204874d8a5f89c4f11f1addfc79939c06f027534ce2c647fdb41643ac07"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.36.tar.gz"
source_sha256 = "d4f6d2fb2761b553b5fa38d41dc767a6cb9f8fecf9c9bf9408bc8099797b1b65"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.36-any-stack-9e5cb204.tgz"
version = "0.0.36"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "f383356847457554c473bc2db5303cf49187f0711fe474f952b4f79c10a63b38"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.52.tar.gz"
source_sha256 = "b3f7936dc64b422db3f991b11321299d61b4e729b8340d03348a63f99567232b"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.52-any-stack-f3833568.tgz"
version = "0.0.52"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "a065d1c1e3482820258d60914a5a7fd1e64fd739ce446abcb8d73370ab178ba7"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.37.tar.gz"
source_sha256 = "40cf904b09402b7db711074a98fe1f7a12774dad382601f2278493b9c2df5a26"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.37-any-stack-a065d1c1.tgz"
version = "0.0.37"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "e8e9a4bc1cb9dbec370817aa071be497dfe0076100d4e2d7024b3ec51c1f754f"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.55.tar.gz"
source_sha256 = "c10aa6a7123d336e8498687b4da3d015d557ebc0c2475519f250716c58679cd6"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.55-any-stack-e8e9a4bc.tgz"
version = "0.0.55"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.55"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.37"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.52"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.36"
