api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "f745d16a7983c38e569547e7bac2ccb1e6ad3053131328ec80567e651a0feb0c"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.29.tar.gz"
source_sha256 = "956d8ac0df54b63f0c28fa336b2d95ad1aabb9da7cf871bc27e749aa9cbba8fb"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.29-any-stack-f745d16a.tgz"
version = "0.0.29"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "8e1ae175e1ad200185f0ef4f34c3eac5e9eb5872deac54b7b643c02262e2d27a"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.40.tar.gz"
source_sha256 = "665377574acebaedae1bd74fb24069f06e22611288a0074c4f0c37a629095d1f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.40-any-stack-8e1ae175.tgz"
version = "0.0.40"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "98f2486dae8c41720ca429adb7af2b8b640019c6d74e0096abf7d18dd5acafb1"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.27.tar.gz"
source_sha256 = "ebced71d767cbbe4c63f995c849c5e11af456aa877d3389c7407c0bbb40cb8bd"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.27-any-stack-98f2486d.tgz"
version = "0.0.27"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "b4e30a5db3f6ecb7aa3eb7c476f9da2e986f1d5e7e5e49a5317705f3de1916ec"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.38.tar.gz"
source_sha256 = "d9edf43a4e8f1faf1217025689d405a528015f564f02337db40fd8d6408951c7"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.38-any-stack-b4e30a5d.tgz"
version = "0.0.38"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.38"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.27"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.40"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.29"
