api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "4cd23fe7e487f003e754ecdf8bf7a21c14b0dc6b69713dea8e711d1a76c3e9fd"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.31.tar.gz"
source_sha256 = "bdaf003ade89c9b87d9c2f4cd727ee8321f22cab0e230b502510c2a247698c49"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.31-any-stack-4cd23fe7.tgz"
version = "0.0.31"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "519d64fc1aaf43dcf7306a6ff65780402b85b9824dcc9103dfa2bddde0660da4"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.41.tar.gz"
source_sha256 = "ff88fc16f907b2c02b09162386b3299cc5ab01583968bd4c0c3fddc99bd01ea1"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.41-any-stack-519d64fc.tgz"
version = "0.0.41"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "98f2486dae8c41720ca429adb7af2b8b640019c6d74e0096abf7d18dd5acafb1"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.27.tar.gz"
source_sha256 = "ebced71d767cbbe4c63f995c849c5e11af456aa877d3389c7407c0bbb40cb8bd"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.27-any-stack-98f2486d.tgz"
version = "0.0.27"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "2ecfa76ab95f18686c42cc3352e04231b72bf422b9a3efb8968e48489e269865"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.40.tar.gz"
source_sha256 = "303da02da6b0f5009bb992e07845c3e187435fdc580d0844c39d2fd9c203f28d"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.40-any-stack-2ecfa76a.tgz"
version = "0.0.40"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.40"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.27"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.41"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.31"
