api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "31b552022352114e24e24b0a790889bb7a612fffed76a9da469756ea82414d67"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.37.tar.gz"
source_sha256 = "0b0a82341896e9690de2c9d1f625bfed086fea3e7849a86f790e2e69daee1ed0"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.37-any-stack-31b55202.tgz"
version = "0.0.37"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "b6204a9ff3fab5b743c619b75db4f9c4a837c3f92aedda213048f8af87a11947"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.53.tar.gz"
source_sha256 = "54e76b0ac8a7b38f2608dbe0a184bae1f06549e50466a4bd403807ea62cf79df"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.53-any-stack-b6204a9f.tgz"
version = "0.0.53"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "62aae3328a9dabaf49c736c13a43d361ac54dcfd79f7030d6c9877f2b677adb9"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.38.tar.gz"
source_sha256 = "2afa849e055ca12a845c06fac3ba492ee8130d1ef17bc64941bf1a1a8318d01d"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.38-any-stack-62aae332.tgz"
version = "0.0.38"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "c715f9e6e1ddec369ee0ff64c13ca5a9304a84a39634cb2fa8f2b494d05c54dd"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.57.tar.gz"
source_sha256 = "ff0695dc7970b073de8f3b4a29c6e0edf3da646a7b0d75cee042fe9ae7aaae61"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.57-any-stack-c715f9e6.tgz"
version = "0.0.57"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.57"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.38"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.53"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.37"
