api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "ba5652391f8172b687f6aca0e6b8a29d298ee4d4440367687990a86b61d85778"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.81.tar.gz"
    source_sha256 = "c4177d1a1919e3f95472d858a1653c8a58b0d009122369b051f756713713f547"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda_0.0.81_linux_noarch_any-stack_ba565239.tgz"
    version = "0.0.81"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "16cd4d8b6343f3a809b5fd2988c891cbd95f3ca353db0be48af0a1ebe4a10c54"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.105.tar.gz"
    source_sha256 = "c0233d3ada0d17360f2c83aebe0fc705932cd9ce0d0634c4f9e2132f5d1d0ce0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip_0.0.105_linux_noarch_any-stack_16cd4d8b.tgz"
    version = "0.0.105"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "4c0f8c178aeba0434b13df4d27d03e33ce2716e02f3c1337a7600f8d038732f7"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.86.tar.gz"
    source_sha256 = "e47d9cb876558e899d076895796a4fb7295fcb84aac00d775603a98e8df1305f"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv_0.0.86_linux_noarch_cflinuxfs3_4c0f8c17.tgz"
    version = "0.0.86"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "7fcc77266c570dd2b1260ae583031cf4200f7b17b42e105c4c0ac732010b8caa"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.113.tar.gz"
    source_sha256 = "c9235f0f88240d5b592b3ae8d2911fafd3532432a6b3ad86e44fabb109bf3e74"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime_0.0.113_linux_noarch_cflinuxfs3_7fcc7726.tgz"
    version = "0.0.113"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.113"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.86"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.105"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.81"
