api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "675c3530970843552aa67d2bd3624bacf8e093a7cf4bb00e3014c0d9d68572db"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.58.tar.gz"
    source_sha256 = "ce132e43377cb7c0b59f05c649ad68c6a8bd344d13d3c0eafdb686017a83e811"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.58-any-stack-675c3530.tgz"
    version = "0.0.58"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "41063e751fad8cfa46c476f8e05c27301cdb13e9abbfc26132293cf273ba6355"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.81.tar.gz"
    source_sha256 = "52216db94ce1496a5e3cd8dfe320e0ea33144dfaa1bf6038c2547de49b4a987a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.81-any-stack-41063e75.tgz"
    version = "0.0.81"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "4e8bdaccc646a777468a55924bea7ae05c0efa81bcd9287b8a55fa3247ecfc67"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.66.tar.gz"
    source_sha256 = "9ee1cead4cc32e38a60d65b3aa038d11216abc33b42acebb6e9c159102a97a58"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.66-any-stack-4e8bdacc.tgz"
    version = "0.0.66"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "40227ff62245bdbc5cf0f2e08190889bcc98cb53321245ebf155cf6191238328"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.83.tar.gz"
    source_sha256 = "a3e1f8efb2a5603045deb1688f518b6227265dc5bdce0f31e9d034692d34700d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.83-any-stack-40227ff6.tgz"
    version = "0.0.83"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.83"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.66"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.81"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.58"
