api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "44369e3fd1cbdafce2796e8b95970405029df3178317615ad7b2dbce0f7543d6"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.50.tar.gz"
    source_sha256 = "0f471705abe3f67bda7562011b151509fe6aa7515666d84ef538c4c8594aea6a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.50-any-stack-44369e3f.tgz"
    version = "0.0.50"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "7c9fe0329db42dc2801a31ce7460b6f95b5ede80b0887c30ee669899ed58e0f2"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.70.tar.gz"
    source_sha256 = "d9bdfcca82ae215995ce051c12a7c0845e2e196b20f940a6a298c7785ea3b874"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.70-any-stack-7c9fe032.tgz"
    version = "0.0.70"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "7c8589b4d9cc0ddedca3b620af14c8ba121d68c49d73f121b736c492d64ab4c8"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.56.tar.gz"
    source_sha256 = "6c83e5feb66ace19dd58305baa390be9d07bba4bb38fbb756305004be09d871a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.56-any-stack-7c8589b4.tgz"
    version = "0.0.56"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "38d336d8fa5136788aa17b93ebfd114f52f0f793e9c11be3ef4c8a8aeb9ce1bd"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.70.tar.gz"
    source_sha256 = "060595e5b9682c020766c440d4a431b760c7c865241c970b4cf2cf269445374d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.70-any-stack-38d336d8.tgz"
    version = "0.0.70"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.70"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.56"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.70"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.50"
