api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "a04ecdab7ff89e7dac088b8500711d948b0c2ac648dbc348e9e496d128775ba7"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.16.tar.gz"
source_sha256 = "349e4861f3841d6c5b2e70c8c2186c3246926e7b28c40a05c485d7e9919283bc"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.16-any-stack-a04ecdab.tgz"
version = "0.0.16"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "f9d3df9451daee690e0a0a25d8d839b5d4da45ccf84143d1c8786fd105474fe2"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.24.tar.gz"
source_sha256 = "116089c5f71b87e3a3ddf3b19eaa7d7d3421c2e6ef4ca5345948c312bfe754e4"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.24-any-stack-f9d3df94.tgz"
version = "0.0.24"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "ef655540c6165828ed6d4a70afd8ea4e1ea99fb6641eb8864616345d9ef6a82b"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.15.tar.gz"
source_sha256 = "2cdb50490f6cb165aa61689c59c563198162f71ebce78735c1fadd559654121e"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.15-any-stack-ef655540.tgz"
version = "0.0.15"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "f9135cba4439e7f571fea1e5cf5f815bba77d0a855a1780cd69760e72f41289d"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.26.tar.gz"
source_sha256 = "71a2feb83a30730ac4d5c2bb3969879a64c4c4065dc3da61d8a731b4ae66b5f8"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.26-any-stack-f9135cba.tgz"
version = "0.0.26"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.26"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.15"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.24"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.16"
