api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "9e5cb204874d8a5f89c4f11f1addfc79939c06f027534ce2c647fdb41643ac07"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.36.tar.gz"
source_sha256 = "d4f6d2fb2761b553b5fa38d41dc767a6cb9f8fecf9c9bf9408bc8099797b1b65"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.36-any-stack-9e5cb204.tgz"
version = "0.0.36"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "b6204a9ff3fab5b743c619b75db4f9c4a837c3f92aedda213048f8af87a11947"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.53.tar.gz"
source_sha256 = "54e76b0ac8a7b38f2608dbe0a184bae1f06549e50466a4bd403807ea62cf79df"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.53-any-stack-b6204a9f.tgz"
version = "0.0.53"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "a065d1c1e3482820258d60914a5a7fd1e64fd739ce446abcb8d73370ab178ba7"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.37.tar.gz"
source_sha256 = "40cf904b09402b7db711074a98fe1f7a12774dad382601f2278493b9c2df5a26"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.37-any-stack-a065d1c1.tgz"
version = "0.0.37"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "c715f9e6e1ddec369ee0ff64c13ca5a9304a84a39634cb2fa8f2b494d05c54dd"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.57.tar.gz"
source_sha256 = "ff0695dc7970b073de8f3b4a29c6e0edf3da646a7b0d75cee042fe9ae7aaae61"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.57-any-stack-c715f9e6.tgz"
version = "0.0.57"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.57"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.37"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.53"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.36"
