api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "31b552022352114e24e24b0a790889bb7a612fffed76a9da469756ea82414d67"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.37.tar.gz"
    source_sha256 = "0b0a82341896e9690de2c9d1f625bfed086fea3e7849a86f790e2e69daee1ed0"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.37-any-stack-31b55202.tgz"
    version = "0.0.37"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "06cc58b3c1b71593f5eece82dae855bbee58e0a5fd1bbe98dee5c91c7c7cc346"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.40.tar.gz"
    source_sha256 = "1c6ad686cb8dca73c7cbd855a1137eaea370375528ead735e0fe0d9f1dd9ecd1"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.40-any-stack-06cc58b3.tgz"
    version = "0.0.40"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "06cc58b3c1b71593f5eece82dae855bbee58e0a5fd1bbe98dee5c91c7c7cc346"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.40.tar.gz"
    source_sha256 = "1c6ad686cb8dca73c7cbd855a1137eaea370375528ead735e0fe0d9f1dd9ecd1"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.40-any-stack-06cc58b3.tgz"
    version = "0.0.40"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "e0c33ed3147d73205cd77b7eff3f9dbed5601f70d1d49c479a3f6762992e0d43"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.56.tar.gz"
    source_sha256 = "2507eb2bfcc4e87403d3822c75603762c8b06e411277b8b92440000202c00c14"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.56-any-stack-e0c33ed3.tgz"
    version = "0.0.56"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "10db078debb44c57fd137343cbc3d03d289a4a4042d9aa1edbc20ff3e4121856"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.62.tar.gz"
    source_sha256 = "960caac14d7832f1ec3df1c982596ed497874b4d191be2152f3407007a556230"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.62-any-stack-10db078d.tgz"
    version = "0.0.62"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "10db078debb44c57fd137343cbc3d03d289a4a4042d9aa1edbc20ff3e4121856"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.62.tar.gz"
    source_sha256 = "960caac14d7832f1ec3df1c982596ed497874b4d191be2152f3407007a556230"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.62-any-stack-10db078d.tgz"
    version = "0.0.62"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "5a95f48f7866623dc2cff2270f3dad14a1e7eb5b24bd6f8fad328784dc076acd"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.41.tar.gz"
    source_sha256 = "45d6b836a03a85200b938e10d4507a60c4041b9715e63d6576fc3681b68a083b"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.41-any-stack-5a95f48f.tgz"
    version = "0.0.41"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "2c279df16e5355becbdd6a88d3b1844d3a31b185de15a736b5ff33b7b4f7dbc0"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.45.tar.gz"
    source_sha256 = "d0008d058a7fadf637dfd043ccab9c987a00deff17a4d60b7a080d193ae8aefc"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.45-any-stack-2c279df1.tgz"
    version = "0.0.45"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "2c279df16e5355becbdd6a88d3b1844d3a31b185de15a736b5ff33b7b4f7dbc0"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.45.tar.gz"
    source_sha256 = "d0008d058a7fadf637dfd043ccab9c987a00deff17a4d60b7a080d193ae8aefc"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.45-any-stack-2c279df1.tgz"
    version = "0.0.45"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "e1cd806fbc03b5b9d29a3331afc3a6954c5affc8f02dd86996d21b673b828a2a"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.60.tar.gz"
    source_sha256 = "97503a69f1165b4b0df7b790e154923d97cb0b2ca9881a1ffaa7b9bf2da35938"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.60-any-stack-e1cd806f.tgz"
    version = "0.0.60"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "161ae45de96c59d2541166ddbe0c703e5026ab1073334d190b9606314870756b"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.61.tar.gz"
    source_sha256 = "82e92857b2a1dc1d6c67414a0827061ccf4c34f7df21c44b58f7e17889d56e28"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.61-any-stack-161ae45d.tgz"
    version = "0.0.61"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "161ae45de96c59d2541166ddbe0c703e5026ab1073334d190b9606314870756b"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.61.tar.gz"
    source_sha256 = "82e92857b2a1dc1d6c67414a0827061ccf4c34f7df21c44b58f7e17889d56e28"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.61-any-stack-161ae45d.tgz"
    version = "0.0.61"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.62"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.62"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.40"

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.40"

