api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "09062697e6d580b12cef0c6085edee2606d69ec66eef2a285f73b9c23b344aaf"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.80.tar.gz"
    source_sha256 = "67e3087f18e73f5c3437a214828d3d43a0584b7526a6169e069b21007ac54938"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda_0.0.80_linux_noarch_any-stack_09062697.tgz"
    version = "0.0.80"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "49a2c31fb537cc18a9a327324379ee3476b544f3cfdf5f8cd9207ecdb282c85c"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.104.tar.gz"
    source_sha256 = "c82255d3750329582232a84460483275e5945a72b080b002ff6d4bc98d244540"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip_0.0.104_linux_noarch_any-stack_49a2c31f.tgz"
    version = "0.0.104"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "41c35f3d29719803668c1fdc7d945ec506256b3b009b2b5b211bc5a5177db441"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.85.tar.gz"
    source_sha256 = "d56fc4b2de36f03302494f54eff9052ddf36b0eb927395ec501f26208e3219ba"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv_0.0.85_linux_noarch_cflinuxfs3_41c35f3d.tgz"
    version = "0.0.85"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "87cc1e5721cf4c295446f41522dcb23a7abd6545c3d99952ed2f564b91af52ef"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.110.tar.gz"
    source_sha256 = "b21d7c496c71bf617ae5544976eef9106a886a4dfdcab6fd197b23f0e15a028b"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.110-cflinuxfs3-87cc1e57.tgz"
    version = "0.0.110"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.110"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.85"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.104"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.80"
