api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "dce7dd4ea56e79318e97d78386c8eac89d40cc00a615ea9513f4bac0921f1947"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.67.tar.gz"
    source_sha256 = "d17dcdc251ade494985c0a976f373d77685fb785e0bf733a1d53ae7855aa9e93"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.67-any-stack-dce7dd4e.tgz"
    version = "0.0.67"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "fa60da5b3274c454b0e359c1d57770517e7593205d228bc1d9f7750cb93c3cc9"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.90.tar.gz"
    source_sha256 = "ae9805d36fb71c5d2d6ff4aa8a8ac676cdcd8606b3c9aac1d3a32d301d990e74"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.90-any-stack-fa60da5b.tgz"
    version = "0.0.90"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "739f9953fd03b5defce3300877593ea86b2791a79af984c44bfef10f0fbd87cf"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.72.tar.gz"
    source_sha256 = "6bbd22557e8de0715adcde789c3ef6742bec0f85b8fd0694c708a87e91379b0c"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.72-cflinuxfs3-739f9953.tgz"
    version = "0.0.72"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "bd7c453bc97e17901f8eeddb6229dd914b171216b84ff15e114b59673e0bfc9b"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.93.tar.gz"
    source_sha256 = "8c8a06af6a321a13934b80676489c20f852ed3ef6dae7b91a00e49d3ca7232bc"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.93-cflinuxfs3-bd7c453b.tgz"
    version = "0.0.93"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.93"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.72"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.90"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.67"
