api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "40ce60cdae789ac9525f26aac1c8ae98c1353f255867870849d0a5a8fc294ced"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.51.tar.gz"
    source_sha256 = "b0f733765c0217475d3be184cfbaf6d825ac48881113b5c73324c539877228a9"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.51-any-stack-40ce60cd.tgz"
    version = "0.0.51"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "274ea8b73a3fd2ec00a847e8823133c047a16dc8f99cba61744605b92a0ea8ee"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.72.tar.gz"
    source_sha256 = "24abe62aee701598e9922d6e6392f52fbd61a4fcd855f631705a302a5e7a585d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.72-any-stack-274ea8b7.tgz"
    version = "0.0.72"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "bdcc307ef8a3ad427a51b23bba24199a986a4c2e693c091bef11b163422a3801"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.58.tar.gz"
    source_sha256 = "42b5a870c9d2370fca1bd8b549f03201916aeb155e4c84553c9db9d538ae30fe"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.58-any-stack-bdcc307e.tgz"
    version = "0.0.58"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "71e53fff0a6b2b2c158fcba8b3ad3a9947fe25223639738f6bb59d95c5f6678f"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.73.tar.gz"
    source_sha256 = "51051fa94b05ec35b2bb5008fe15172a18c43390c3bd1c597c15c13e7531be22"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.73-any-stack-71e53fff.tgz"
    version = "0.0.73"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.73"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.58"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.72"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.51"
