api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "68926fc575a8e3b7a27c8b8263ce4977e82386521183ce3461588fd13e818096"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.77.tar.gz"
    source_sha256 = "42ec42dac4603b249da8fd8dc645578f6feeb21094d84f1dd42214806f5e172a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.77-any-stack-68926fc5.tgz"
    version = "0.0.77"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "5e00f2c51343a0d4455ef8ac5539bf921ec64af681d64f40c0e2e588c1bbbf0e"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.99.tar.gz"
    source_sha256 = "6fe27f281ba45d22ae9e3104ea43eee993d3536039f4a104e9ee382c352d1952"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.99-any-stack-5e00f2c5.tgz"
    version = "0.0.99"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "94f3c27b95cead7c65dfd5a5eecdaf2cc4b4e16b2b1c95536c8214009c7db9c5"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.81.tar.gz"
    source_sha256 = "93089ac97c0309c96d22d5d68409b733b3b298ba48beec91e3acc7ed695c07ee"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.81-cflinuxfs3-94f3c27b.tgz"
    version = "0.0.81"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "9b91d07adfc1da59012308eed446f1b182c304352f87a736219bd8ac100fcc11"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.104.tar.gz"
    source_sha256 = "85077e58111e129ffa632447d52bd1da0e23812d60b61bd9159a4ea0d3ad1d6c"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.104-cflinuxfs3-9b91d07a.tgz"
    version = "0.0.104"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.104"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.81"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.99"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.77"
