api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "92a247a0770665e0cc134d138932fbe1e1f9b704d5a3cf72db164f728aae048d"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.73.tar.gz"
    source_sha256 = "e7481d73ef85b488e4177109305de69bec8007ea503be7c9e56f71a92127a753"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.73-any-stack-92a247a0.tgz"
    version = "0.0.73"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "08bf21fa01d0bbefb0322cf366b922d97008ea749f329a705ec8ac40dd7ab966"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.95.tar.gz"
    source_sha256 = "c33fc5c7b3266337f2b464586a6bc4a2b406d151818159a05931626fe2de1152"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.95-any-stack-08bf21fa.tgz"
    version = "0.0.95"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "d9b7dccf40a5288ed7af69a27ce8420df73e8655bcf1e38889a6874c2762072d"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.79.tar.gz"
    source_sha256 = "97d59eb79a726f7f4ecfaea9bbd1924cf174d1cdc32c59d7431806df2c909e80"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.79-cflinuxfs3-d9b7dccf.tgz"
    version = "0.0.79"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "995cc5c3c5e64de994f537dfda82a63133b594ab5ae7f1756daeb6f93166006e"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.99.tar.gz"
    source_sha256 = "7b7ca50a330a665e98b7fb1fa0ca67601ed294b7df062af77a1f47215776a530"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.99-cflinuxfs3-995cc5c3.tgz"
    version = "0.0.99"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.99"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.79"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.95"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.73"
