api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "82a96c1022c127072b651665cf73de43e598866918c9c9adbb8546dcac7ff33d"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.61.tar.gz"
    source_sha256 = "c3e40d08124f2b7dd9d08f1ac2b6b6da49cd6a14b2d08d566c216f91f8ec3564"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.61-any-stack-82a96c10.tgz"
    version = "0.0.61"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "1064a0eab32e755e409656a4b68b783d6b08a50c9d567eee6ca52af6e83b4a87"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.83.tar.gz"
    source_sha256 = "f7e327756a59f3b1f71382c82e1d9ce0ec6843d21cc575519141e35cbd117cdc"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.83-any-stack-1064a0ea.tgz"
    version = "0.0.83"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "f58c91173da2ff1580da2624b1b8f97e8bc5e813d1e4607e9c17eff1037ef706"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "c1364868bdc1e47fa0c060480d9c77a53640c9e710047eaf9cb5deb3f49efae7"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.68-any-stack-f58c9117.tgz"
    version = "0.0.68"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "c0c9231611ff59b76c955351037fb9acfaecc5bc10073fd8950513dc179fbf65"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.86.tar.gz"
    source_sha256 = "761951e26405088cc276162d7b0223c904da7ff8b724acb89acfa1fcc1f3159e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.86-any-stack-c0c92316.tgz"
    version = "0.0.86"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.86"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.68"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.83"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.61"
