api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "527406787b183ab6bfcbee66e9400d5aae0e9741b49df23e48bc2adbda5740ae"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.21.tar.gz"
source_sha256 = "307610def9d1d9f9f87e85b426bec8e49848973c97d2d8fdde660f218be7c356"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.21-any-stack-52740678.tgz"
version = "0.0.21"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "238ac28199ea1de73dd5b70a72eb9c6ee8093b0b677aa742520c594b287a9a61"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.32.tar.gz"
source_sha256 = "347b5113017a2e17e8bf580e6f09ddc87386c405fa23675bd1322fa3683f85a7"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.32-any-stack-238ac281.tgz"
version = "0.0.32"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "62bb81b7f627b67154895363ebaa7143ab1fad60f729fb0d36c8a14557f4525c"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.20.tar.gz"
source_sha256 = "058c9f6f9099b9c50fc82b2b80fd4942cb1dfd0fdb2a976ff88e3e9585d6e61e"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.20-any-stack-62bb81b7.tgz"
version = "0.0.20"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "277c60c3514bc9640ca687f9ea499a0732cc1c1fc43ee7ffc4db27135c07e926"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.29.tar.gz"
source_sha256 = "2e6a47bd7cd82b554915ed9efc0b75e0dd454e6a76160d39aec0c1b824989154"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.29-any-stack-277c60c3.tgz"
version = "0.0.29"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.29"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.20"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.32"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.21"
