api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "1b91014ee4ccf7b8001a9457cfd72ac32fa3bca557d01a27a6515ff65042b53e"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.44.tar.gz"
    source_sha256 = "ab9fc15c9650c17e1239ad83c702921b31d3902067f7816b6b89ac7e06982552"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.44-any-stack-1b91014e.tgz"
    version = "0.0.44"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "11e0c97c567594ac83f4eae61400a94ad7d78c49ba1c0d890233c297887367a6"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.63.tar.gz"
    source_sha256 = "35f39c4eb414d5530b171bca5c183a6a37ed93f2c2e66269d0ccc12fbae7e507"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.63-any-stack-11e0c97c.tgz"
    version = "0.0.63"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "b37dca8be4b8bb475a782978fd94e4feb9946eeda3824b6cb9d1f694fcb6738f"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.50.tar.gz"
    source_sha256 = "d570c82e587805ac2f98ca1cd68b4e9c34574d8a09f9a8ae58be0ffc95cef2ab"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.50-any-stack-b37dca8b.tgz"
    version = "0.0.50"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "1dd55ba962aad4466ef8dfecfe11347cd0eb36352c8bfb78ec145e29253ceb39"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.65.tar.gz"
    source_sha256 = "d5f058f867efdce97485aab986db713b308124e0ac0c86d01eb0d2bdf57c35a8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.65-any-stack-1dd55ba9.tgz"
    version = "0.0.65"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.65"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.50"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.63"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.44"
