api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "31b552022352114e24e24b0a790889bb7a612fffed76a9da469756ea82414d67"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.37.tar.gz"
    source_sha256 = "0b0a82341896e9690de2c9d1f625bfed086fea3e7849a86f790e2e69daee1ed0"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.37-any-stack-31b55202.tgz"
    version = "0.0.37"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "31b552022352114e24e24b0a790889bb7a612fffed76a9da469756ea82414d67"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.37.tar.gz"
    source_sha256 = "0b0a82341896e9690de2c9d1f625bfed086fea3e7849a86f790e2e69daee1ed0"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.37-any-stack-31b55202.tgz"
    version = "0.0.37"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "31b552022352114e24e24b0a790889bb7a612fffed76a9da469756ea82414d67"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.37.tar.gz"
    source_sha256 = "0b0a82341896e9690de2c9d1f625bfed086fea3e7849a86f790e2e69daee1ed0"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.37-any-stack-31b55202.tgz"
    version = "0.0.37"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "e0c33ed3147d73205cd77b7eff3f9dbed5601f70d1d49c479a3f6762992e0d43"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.56.tar.gz"
    source_sha256 = "2507eb2bfcc4e87403d3822c75603762c8b06e411277b8b92440000202c00c14"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.56-any-stack-e0c33ed3.tgz"
    version = "0.0.56"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "1581f1892b6f6e3d7babe060038bc03755b3285058118837b5a83824aabebdbd"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.58.tar.gz"
    source_sha256 = "ad7da680395a830e13b03b667d3f4bbceeb32da670d412d05d5529dcf7aa4a2c"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.58-any-stack-1581f189.tgz"
    version = "0.0.58"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "1581f1892b6f6e3d7babe060038bc03755b3285058118837b5a83824aabebdbd"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.58.tar.gz"
    source_sha256 = "ad7da680395a830e13b03b667d3f4bbceeb32da670d412d05d5529dcf7aa4a2c"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.58-any-stack-1581f189.tgz"
    version = "0.0.58"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "5a95f48f7866623dc2cff2270f3dad14a1e7eb5b24bd6f8fad328784dc076acd"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.41.tar.gz"
    source_sha256 = "45d6b836a03a85200b938e10d4507a60c4041b9715e63d6576fc3681b68a083b"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.41-any-stack-5a95f48f.tgz"
    version = "0.0.41"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "ea3899cc415f9a6af974bcd971adadf1a4fff0a735083c831f2ff7a1340000a0"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.42.tar.gz"
    source_sha256 = "e543f674981ec24b9532531b3754d77c17b5e5d4f59addac52be70c81ab26486"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.42-any-stack-ea3899cc.tgz"
    version = "0.0.42"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "ea3899cc415f9a6af974bcd971adadf1a4fff0a735083c831f2ff7a1340000a0"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.42.tar.gz"
    source_sha256 = "e543f674981ec24b9532531b3754d77c17b5e5d4f59addac52be70c81ab26486"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.42-any-stack-ea3899cc.tgz"
    version = "0.0.42"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "e1cd806fbc03b5b9d29a3331afc3a6954c5affc8f02dd86996d21b673b828a2a"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.60.tar.gz"
    source_sha256 = "97503a69f1165b4b0df7b790e154923d97cb0b2ca9881a1ffaa7b9bf2da35938"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.60-any-stack-e1cd806f.tgz"
    version = "0.0.60"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "e1cd806fbc03b5b9d29a3331afc3a6954c5affc8f02dd86996d21b673b828a2a"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.60.tar.gz"
    source_sha256 = "97503a69f1165b4b0df7b790e154923d97cb0b2ca9881a1ffaa7b9bf2da35938"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.60-any-stack-e1cd806f.tgz"
    version = "0.0.60"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "e1cd806fbc03b5b9d29a3331afc3a6954c5affc8f02dd86996d21b673b828a2a"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.60.tar.gz"
    source_sha256 = "97503a69f1165b4b0df7b790e154923d97cb0b2ca9881a1ffaa7b9bf2da35938"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.60-any-stack-e1cd806f.tgz"
    version = "0.0.60"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.58"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.37"


  [[order.Group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.57"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.37"
