api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "7f2fed9e349684db3cfb0e11c09099e2e5986822356575b5cb476ad8c8fe7431"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.63.tar.gz"
    source_sha256 = "4b19459c33a911398f6e256a36e5b191dc5dce7441a4a68f8bab79a8278aa084"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.63-any-stack-7f2fed9e.tgz"
    version = "0.0.63"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "33af3a741386750478f5206d7f2c8e2ee4523504c6b41eb63b29e57d6dfbc880"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.86.tar.gz"
    source_sha256 = "b7f7bd06c7b6e4d012eb48cbb0c8b1d9f2beb910c42e5efdc9246f4df83309bb"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.86-any-stack-33af3a74.tgz"
    version = "0.0.86"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "fbe0a444d157228a78a0b7b99048dccbfa4770429f6d02d20b1573112512803f"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.70.tar.gz"
    source_sha256 = "21627b1ef210c0779b8aae764f6522ea3b186bd646101a26dbdfbe801fd30750"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.70-any-stack-fbe0a444.tgz"
    version = "0.0.70"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "04e8ecfe2729e385c06854a30bb7c3f99964bf4c009ecf101823396f0ea160b3"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.89.tar.gz"
    source_sha256 = "bbdea455632a6f8eee0ad43075ed5e8fd1ec91e641ab7fefdd7032f2c8e0e656"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.89-any-stack-04e8ecfe.tgz"
    version = "0.0.89"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.89"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.70"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.86"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.63"
