api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "91a40360720df88529be9eec60ef446b6a41b77fb178f1270ea89e19f24e6a3e"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.54.tar.gz"
    source_sha256 = "6bb2c8d9c25576fe6860ea2ad7b41f07c2329cede3b64c0c66e1502c56dfa5af"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.54-any-stack-91a40360.tgz"
    version = "0.0.54"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "d7efca7831fcc260bb260d2a3995d6f41342dabfd4ccffbaffebdb396b0271a8"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.76.tar.gz"
    source_sha256 = "56527c135c24eb574ddec8847d080af773a74dc31f0cd9972b04e28831ab587b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.76-any-stack-d7efca78.tgz"
    version = "0.0.76"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "a6880ed2a26bf8fdb5ae2381a0bfd56f2e3d7af39d69625d113398a04d02b0dd"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.61.tar.gz"
    source_sha256 = "a03e24c8d4132bf00965d8285ce2fd1b8b2fef544ad1801e57481b88112f2ed2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.61-any-stack-a6880ed2.tgz"
    version = "0.0.61"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "999265f3736a31affd2f00523a4facc699ef6b5e95d4168721269af6acbef07b"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.79.tar.gz"
    source_sha256 = "ca4d03b02c05f7440a1d16474655ce3ca43b377ec4ce266704377e3cf76ffe48"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.79-any-stack-999265f3.tgz"
    version = "0.0.79"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.79"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.61"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.76"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.54"
