api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "91a8bcae25a1706de65cb08e2d95b55adf79e17940635ad0326adba29a0c5b51"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.32.tar.gz"
source_sha256 = "c7d6d18090a60bd2442c37371b3f908e485463f071a9aba79f18832d16746188"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.32-any-stack-91a8bcae.tgz"
version = "0.0.32"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "ed0b5d751dc012bfdeff104ac11651ad23903a58e5e9748395d182e8f97202ac"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.42.tar.gz"
source_sha256 = "1efabdd55b2d969b09246ed2ed1957195c08f0eb965986bfeb390f900914b403"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.42-any-stack-ed0b5d75.tgz"
version = "0.0.42"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "d6008b8d36d052bfb45aafb14c12faa868ed87a46d1071a1f221edb133d0ccb4"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.28.tar.gz"
source_sha256 = "add23bfda5902f555d11b243a7f17c2d6457da9b404a8d867d4cf1e4ac4555ad"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.28-any-stack-d6008b8d.tgz"
version = "0.0.28"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "69642707b75dec494cde6443b0f01dfc75ce0a4fd6682bcbcbd6d87e4d4da08b"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.41.tar.gz"
source_sha256 = "dd31ea41c91b48d9f8b4e533440a849e2ff3d5159430298b2111dd9ec7b06b7b"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.41-any-stack-69642707.tgz"
version = "0.0.41"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.41"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.28"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.42"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.32"
