api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "e0a75733c62e9caf27a380297ec064a675cc75d1fdca336b9658970ed8e88a41"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.82.tar.gz"
    source_sha256 = "96168160c6c887a13f5e8c6bf14a26cca5df129c6fb7d408ca107f9ce77bd68b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda_0.0.82_linux_noarch_any-stack_e0a75733.tgz"
    version = "0.0.82"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "801c7b7ba25f7daf2c8670eb790a237ee78967ed8f31238e3617a7ada73eec27"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.106.tar.gz"
    source_sha256 = "e1993f6fce86fca618401203f8a8a7d279ace4cfef30cd22678ecb8b32d37a3c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip_0.0.106_linux_noarch_any-stack_801c7b7b.tgz"
    version = "0.0.106"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "85028101c5558343e81c61065ed10da0ca52f4f4e190f7140d77a1b9c3cffffa"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.87.tar.gz"
    source_sha256 = "feacbb8e2e1c96e3c32be80ab22482a5b9dfc2647baee0f7f3f98107dadefc06"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv_0.0.87_linux_noarch_cflinuxfs3_85028101.tgz"
    version = "0.0.87"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "e2cf2cc59e1f7286ef705f3bf991ae47d86c694bb6bddc1f0bb03fe3593ad95a"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.114.tar.gz"
    source_sha256 = "46cf087ca95890d96fe3bc2ccc834396b1b83702d0bceacf7a006315e64f40ae"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime_0.0.114_linux_noarch_cflinuxfs3_e2cf2cc5.tgz"
    version = "0.0.114"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.114"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.87"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.106"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.82"
