api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "6281d187d54a3f2d45646ef65a18daf5193f941993968ccd543235a0538a01e0"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.34.tar.gz"
source_sha256 = "fd9caebabb43a99fd044c9f8a5c5a998f914ebcfbcc8d949130d80fd404295a4"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.34-any-stack-6281d187.tgz"
version = "0.0.34"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "f664d89182e46fa34dcf4c3ac061d60db253e2033e72d10d4c3980625f3a05d4"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.44.tar.gz"
source_sha256 = "6a35d77c488199d226cb3c51dc1fc1d7490c17624c261955f56b516a8f999fb8"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.44-any-stack-f664d891.tgz"
version = "0.0.44"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "ae4ca9a40bf709b4f47603a99b3d60e92ab15e7489e8edf5f1b678b90a130506"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.30.tar.gz"
source_sha256 = "d7bb4461fa8e6e73ce561293ba13562bcd1a0cfac337d965a36e83db8a55e10a"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.30-any-stack-ae4ca9a4.tgz"
version = "0.0.30"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "9772d7138d27018828dcf35e29bb61dc8e6ba6a5b43e8077ed72b36751c3f18b"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.43.tar.gz"
source_sha256 = "50f6a71289f007934c7db80075e0bbd12d444b3450e9527102a138f480f9bbea"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.43-any-stack-9772d713.tgz"
version = "0.0.43"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.43"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.30"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.44"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.34"
