api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "31b552022352114e24e24b0a790889bb7a612fffed76a9da469756ea82414d67"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.37.tar.gz"
source_sha256 = "0b0a82341896e9690de2c9d1f625bfed086fea3e7849a86f790e2e69daee1ed0"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.37-any-stack-31b55202.tgz"
version = "0.0.37"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "c992e3118f14cbe05ed11e03bda3519c24fc2b68540636a4f0189f3a928d6f91"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.54.tar.gz"
source_sha256 = "37bd87a9890987a3643efab1af46e9b7bb321fae83f07086754286071a891e29"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.54-any-stack-c992e311.tgz"
version = "0.0.54"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "2e8bd8c5cdcb98407bde4a23e5831cfb4fc1578f062b3475fa1ddf924010d948"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.39.tar.gz"
source_sha256 = "84a1f3e4ee47270d9e18139182a89eb98445898d77c58e926abc8a263c173412"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.39-any-stack-2e8bd8c5.tgz"
version = "0.0.39"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "c715f9e6e1ddec369ee0ff64c13ca5a9304a84a39634cb2fa8f2b494d05c54dd"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.57.tar.gz"
source_sha256 = "ff0695dc7970b073de8f3b4a29c6e0edf3da646a7b0d75cee042fe9ae7aaae61"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.57-any-stack-c715f9e6.tgz"
version = "0.0.57"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.57"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.39"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.54"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.37"
