api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "b89013cc9a5ff4b73cbcf7e2413f91f69f18e4fc302514dac17fb0bd3522e62b"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.70.tar.gz"
    source_sha256 = "e80d2a332b5baf0e5977b01e267a301128f5e098f47088d057204e2daa300da1"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.70-any-stack-b89013cc.tgz"
    version = "0.0.70"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "389d5e39af974939501a201a1895e1b0f52e309b73a40991683f6bb8fdeec36d"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.91.tar.gz"
    source_sha256 = "fc670fccf8e0f7c2ffe9608e9f8f28460db9ddb15338d2a0c54262bfd2908131"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.91-any-stack-389d5e39.tgz"
    version = "0.0.91"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "7c6d769e038e788555dbe1dab4412a326e34d26ca95285ddcc23399bc7519f7d"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.76.tar.gz"
    source_sha256 = "f8a2ca50908f59298afe62f4f579469ed0d72d39b4fc0ee3647785784b31e23a"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.76-cflinuxfs3-7c6d769e.tgz"
    version = "0.0.76"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "1b2a226864d218b4226f0ef6a84c049e233209471f5c97e441738cb6dc55bdfa"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.96.tar.gz"
    source_sha256 = "d361e62b2690ec4ec8bfa0a8cee2869989210271b954ede121adeecd44a777b6"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.96-cflinuxfs3-1b2a2268.tgz"
    version = "0.0.96"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.96"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.76"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.91"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.70"
