api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "d666b2664efa119192606a31bd681cdfbd38519e0012a21dd054c15b017dda5e"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.78.tar.gz"
    source_sha256 = "6fff9d4285a8e4dd08d528214d725e0bf6804225e2c40b3e39fab789e1960535"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.78-any-stack-d666b266.tgz"
    version = "0.0.78"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "598872b8dbc58b8642fc6054a74b60fa6d17134b1c6d77cb57cf30dbdf4682d5"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.101.tar.gz"
    source_sha256 = "318f9ca5e2fb8170534ac2398bf0953338909df02952081644e6b665fa0502ec"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.101-any-stack-598872b8.tgz"
    version = "0.0.101"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "e4975db4b332de0a5681204e6a4521bc0d7a56b4f55b3a4ce1359d3c79648400"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.84.tar.gz"
    source_sha256 = "6b72e085aef47a7da7ea14ef243b500ecd9abbfe8bd3113e6fac0009a16f798a"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.84-cflinuxfs3-e4975db4.tgz"
    version = "0.0.84"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "87cc1e5721cf4c295446f41522dcb23a7abd6545c3d99952ed2f564b91af52ef"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.110.tar.gz"
    source_sha256 = "b21d7c496c71bf617ae5544976eef9106a886a4dfdcab6fd197b23f0e15a028b"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.110-cflinuxfs3-87cc1e57.tgz"
    version = "0.0.110"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.110"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.84"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.101"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.78"
