api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "c55b66cf8c6af6f630f60fb6d46284b79226b1ad2cdbf9366080fa68e896b2ff"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.49.tar.gz"
    source_sha256 = "28ec431cc0bc703b0cbc06d2dda6f460f6872a2ae9015018edbedff27e9f32c0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.49-any-stack-c55b66cf.tgz"
    version = "0.0.49"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "b7b04e266ee4702b289350e443b7b930f1c9d3b08ad1b983062e20928eb940ab"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "f47426e3eeefa3af51efeb0d16b7c44534e648d9e7d5bc762e8c761634e5bae8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.68-any-stack-b7b04e26.tgz"
    version = "0.0.68"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "79aeac4dcbbeede35ba0744ca94a15922e90930e4926dd43129af7343cd30aca"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.54.tar.gz"
    source_sha256 = "87f3c888b7acf551d46fc7355c908498621fd5047fc8e8dd4943c1ac9b52e328"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.54-any-stack-79aeac4d.tgz"
    version = "0.0.54"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "f1bbd7ea6dffbe4dc5e1516f4eaf38d46bd4b81d3f678e03b3b63a9ab47984b4"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.69.tar.gz"
    source_sha256 = "323e9f073f295d81f12b85f23b2041825c34ed683a3e3492302f4105fa68912a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.69-any-stack-f1bbd7ea.tgz"
    version = "0.0.69"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.69"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.54"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.68"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.49"
