api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "8f155d149c6b038488524efb1badbc27dd0ee982d1c3c58f9c39cb8938224359"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.55.tar.gz"
    source_sha256 = "ccad248efdb7fb6ab9a9c63a7ee98a7482218db7b5b0897892856e178c2bb9a5"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.55-any-stack-8f155d14.tgz"
    version = "0.0.55"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "d7efca7831fcc260bb260d2a3995d6f41342dabfd4ccffbaffebdb396b0271a8"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.76.tar.gz"
    source_sha256 = "56527c135c24eb574ddec8847d080af773a74dc31f0cd9972b04e28831ab587b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.76-any-stack-d7efca78.tgz"
    version = "0.0.76"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "348eed9cabd9b29a831f6e6d543f05ef513784458092b341e1ea1b7402f966c7"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.62.tar.gz"
    source_sha256 = "3adb29ad48c82d15ddd06a128d822f388af8a7275bc5f9a1dfa0d06043a53d07"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.62-any-stack-348eed9c.tgz"
    version = "0.0.62"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "5203d5cc29349b5db5f6f20affb0e436ddc420497dc367b1a55c73c5216d3e51"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.80.tar.gz"
    source_sha256 = "513f387b04164e5f22dd173b6f83b7c5da371d1ce7689ae573ed3beeb0a10177"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.80-any-stack-5203d5cc.tgz"
    version = "0.0.80"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.80"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.62"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.76"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.55"
