api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "9e5cb204874d8a5f89c4f11f1addfc79939c06f027534ce2c647fdb41643ac07"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.36.tar.gz"
source_sha256 = "d4f6d2fb2761b553b5fa38d41dc767a6cb9f8fecf9c9bf9408bc8099797b1b65"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.36-any-stack-9e5cb204.tgz"
version = "0.0.36"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "fd4c61915f18e2401d796fbcd673a05268ce029ece4de60bfd1d48ec097f5e7c"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.48.tar.gz"
source_sha256 = "5485a5411e6704d20d305a955b41767ac991532510e695e1ed53d9a5f1fe288b"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.48-any-stack-fd4c6191.tgz"
version = "0.0.48"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "be9ff2bcc0ad2bf9009c4f850a4bdd3db55d881145c882656c43ccb547af9021"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.34.tar.gz"
source_sha256 = "31b3b625acc1d3289313298ae498ae4c6b085ac23509209f49304579daee3195"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.34-any-stack-be9ff2bc.tgz"
version = "0.0.34"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "3bff9da82de0030da86e6f3c3abf01d812ce01d1c5108430a75dc488d9b5569a"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.49.tar.gz"
source_sha256 = "a51ef6e71123db18ee074ecfb6e741a2719e5cd26ba3c78cac68cbadd9d36a67"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.49-any-stack-3bff9da8.tgz"
version = "0.0.49"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.49"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.34"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.48"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.36"
