api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "a8d388a2267f0e69baa0696be9512d2a76425ff70f24053d595772280e4067a0"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.69.tar.gz"
    source_sha256 = "fcf458d54b61bc3a3ef9f72a44b939b5d7993271d58a1986cac4c08f9ab217f2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.69-any-stack-a8d388a2.tgz"
    version = "0.0.69"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "389d5e39af974939501a201a1895e1b0f52e309b73a40991683f6bb8fdeec36d"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.91.tar.gz"
    source_sha256 = "fc670fccf8e0f7c2ffe9608e9f8f28460db9ddb15338d2a0c54262bfd2908131"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.91-any-stack-389d5e39.tgz"
    version = "0.0.91"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "f7b62d561bf07cc98c9daf358a73a2b8635558e3c955f8db02fb7b51ded22897"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.73.tar.gz"
    source_sha256 = "cf57a8b79658d7eb16acd64d6c8106e7e6b710b278ef03dfe0402c2643a352d9"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.73-cflinuxfs3-f7b62d56.tgz"
    version = "0.0.73"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "88435695759a310317063bb83bea31e6e2e762777cc088881cd697fb7838136a"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.95.tar.gz"
    source_sha256 = "e390670990ad20236b36647b9af8aa02a879fdf6ce70cfc57b403c5ba7292fc2"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.95-cflinuxfs3-88435695.tgz"
    version = "0.0.95"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.95"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.73"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.91"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.69"
