api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "3dd737bffe596c859eaaffb84efc121bb5f69896e6664d5896154cd917099f50"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.62.tar.gz"
    source_sha256 = "9a6200d13efe8d4f0c8e03c9197919fae0ef8f4368f826fba5a34d0a4af5f132"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.62-any-stack-3dd737bf.tgz"
    version = "0.0.62"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "507d266ccd63b0b46a12ab35f790e9ec220e9f143be8fff6c5184c20b015ef8f"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.85.tar.gz"
    source_sha256 = "63c361ca8e15e9f7ec644a2a5949b56517317dccf79de0ecf8b4bb06ca0d535d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.85-any-stack-507d266c.tgz"
    version = "0.0.85"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "7a4a56ef313a9fbb0831b9f833673fbbe9774b878c4ef24e355726cad9ffbb4c"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.69.tar.gz"
    source_sha256 = "e904ac713f32765b76885f5c0ceaeaacf66f4a1d89f78434adaf61e373517549"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.69-any-stack-7a4a56ef.tgz"
    version = "0.0.69"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "200e1079ff6febe982af9502399eb7695f5a18226d73306172494ccc5cbeeb86"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.87.tar.gz"
    source_sha256 = "57c0ef8150e9ffd9062f41004bc8369249752a934be27b357d331dce22da4257"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.87-any-stack-200e1079.tgz"
    version = "0.0.87"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.87"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.69"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.85"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.62"
