api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "f8d1505ea42f35c2ee211ea84aae75cd04b10783252548bd1846f76637b0aa92"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.20.tar.gz"
source_sha256 = "94c773335288eaa7c39c60fef6f2d996fc55f5fd128b49f9a517129487dbb4fe"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.20-any-stack-f8d1505e.tgz"
version = "0.0.20"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "03a9b2bc7cc75ed1f39cd497525e4c72e5f497064386a275552dea45c8bc1104"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.30.tar.gz"
source_sha256 = "d42e746446fe3fcd78150e11c881bdfafd180323ff66391f15a42e84bc3e5f03"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.30-any-stack-03a9b2bc.tgz"
version = "0.0.30"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "62bb81b7f627b67154895363ebaa7143ab1fad60f729fb0d36c8a14557f4525c"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.20.tar.gz"
source_sha256 = "058c9f6f9099b9c50fc82b2b80fd4942cb1dfd0fdb2a976ff88e3e9585d6e61e"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.20-any-stack-62bb81b7.tgz"
version = "0.0.20"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "277c60c3514bc9640ca687f9ea499a0732cc1c1fc43ee7ffc4db27135c07e926"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.29.tar.gz"
source_sha256 = "2e6a47bd7cd82b554915ed9efc0b75e0dd454e6a76160d39aec0c1b824989154"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.29-any-stack-277c60c3.tgz"
version = "0.0.29"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.29"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.20"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.30"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.20"
