api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "5873fda8e56a12455ac6f38394475f4d17808f28ca0d862e1b7d0a428b69e32f"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.83.tar.gz"
    source_sha256 = "1e1378cd637ebcf3c816d11127fed87f037684345d73d0b761a78fbc062009ce"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda_0.0.83_linux_noarch_any-stack_5873fda8.tgz"
    version = "0.0.83"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "e163e3dee636ed6ea3e77c595cb055f8e8ca4d91edd6811a0d602d9ca8e2c242"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.108.tar.gz"
    source_sha256 = "fa72ad3dda17184fe4a9bf802d2aa1a38e72a23abd8fed177fd134878e2d0725"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip_0.0.108_linux_noarch_any-stack_e163e3de.tgz"
    version = "0.0.108"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "a1a5dc848d1145bf7bb4fefdb7fa014e49211394f7a24df6e48f03fb08759ea5"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.89.tar.gz"
    source_sha256 = "2fb07cdc77aed0be4f5c3df72212abd6a72d7e87601aac721285767bb4f3ffb6"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv_0.0.89_linux_noarch_cflinuxfs3_a1a5dc84.tgz"
    version = "0.0.89"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "ee82f55af3b1dc9950b3605d093379313e5ace7c736c2f1e402a4d739dcef0b1"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.115.tar.gz"
    source_sha256 = "63db4dff1b50fdcffd098646d4e43b98cf18066cd886e39808125e6e40ba06f4"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime_0.0.115_linux_noarch_cflinuxfs3_ee82f55a.tgz"
    version = "0.0.115"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.115"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.89"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.108"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.83"
