api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "72b856a132755f61ef8e0c8d972e2a4f3b067033defbd5851e17d655d82bdbce"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.72.tar.gz"
    source_sha256 = "6b538501292ede3f4a0234abe9b8dea1b1159eff3a571e1e1cbf0800e5e80385"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.72-any-stack-72b856a1.tgz"
    version = "0.0.72"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "6a3f6550aca2c7578c21bf90adbc3411ba006abc6ff94700cb21b471873e4b43"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.94.tar.gz"
    source_sha256 = "c5ccd073dc99bd1617ccdaf1477f6e2ce1c9bab97fe8ecfaec05746883bf5ef9"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.94-any-stack-6a3f6550.tgz"
    version = "0.0.94"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "09387926bc67e5560738f202ed0c641ae9ef59a22ba88009fee897891095154a"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.77.tar.gz"
    source_sha256 = "7635f9f1b9bf1f23afac3afc0bc2451f593e33d559d31c3e79401bb3755c8a58"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.77-cflinuxfs3-09387926.tgz"
    version = "0.0.77"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "41f12d30e57204926639e7508e3928f1aeb36697f2db77f4f0c30509471e8da9"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.98.tar.gz"
    source_sha256 = "809352128b1f714160cee048e5597ebf4a6c4eeafb75a3fdbde0b2a690eff89a"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.98-cflinuxfs3-41f12d30.tgz"
    version = "0.0.98"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.98"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.77"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.94"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.72"
