api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "31b552022352114e24e24b0a790889bb7a612fffed76a9da469756ea82414d67"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.37.tar.gz"
source_sha256 = "0b0a82341896e9690de2c9d1f625bfed086fea3e7849a86f790e2e69daee1ed0"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.37-any-stack-31b55202.tgz"
version = "0.0.37"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "23d1f6aa3da0338b5ae0cd7a770b9cdbf95ed024ca4719c6da30a85aa39632bb"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.55.tar.gz"
source_sha256 = "60259a6cb9969d6b66644e712653e6ac2af5bba12bb4b72cd994f87ec9bb78f0"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.55-any-stack-23d1f6aa.tgz"
version = "0.0.55"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "2db2e77c0fc95459bb597a66b58761c16409780ab222e436509f7299c2c8d905"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.40.tar.gz"
source_sha256 = "5edd11f6b2179808c96ac1b5796950ea000ba7217e320b684680e3a2d4211760"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.40-any-stack-2db2e77c.tgz"
version = "0.0.40"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "e1cd806fbc03b5b9d29a3331afc3a6954c5affc8f02dd86996d21b673b828a2a"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.60.tar.gz"
source_sha256 = "97503a69f1165b4b0df7b790e154923d97cb0b2ca9881a1ffaa7b9bf2da35938"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.60-any-stack-e1cd806f.tgz"
version = "0.0.60"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.60"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.40"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.55"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.37"
