api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "7c6cb48a109e65e7cf742e6805ab498152d39a3d3dcaa4da0ed081a6675d4dbb"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.65.tar.gz"
    source_sha256 = "d7d5c4327292c1fa2879481706ca196fb435d1a873bc244dac29884b43cee17a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.65-any-stack-7c6cb48a.tgz"
    version = "0.0.65"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "785c6a614d3c4fee3a1bee676339f2ec64051708967905fe151c7d7a5fd7df92"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.88.tar.gz"
    source_sha256 = "eb7341fe47fc6e7a47d64467a4788d12aa4389d494bda30608dc28e13a18b51f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.88-any-stack-785c6a61.tgz"
    version = "0.0.88"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "739f9953fd03b5defce3300877593ea86b2791a79af984c44bfef10f0fbd87cf"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.72.tar.gz"
    source_sha256 = "6bbd22557e8de0715adcde789c3ef6742bec0f85b8fd0694c708a87e91379b0c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.72-any-stack-739f9953.tgz"
    version = "0.0.72"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "7e297da2f86b891c185ddce8a4ed76905a9c50c5a7ebd0093abf7dbac39a0b9f"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.90.tar.gz"
    source_sha256 = "544531b2892317f7b8d2c35df42489fb02044c4cf56b14558e18ae5ba95cce8d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.90-any-stack-7e297da2.tgz"
    version = "0.0.90"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.90"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.72"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.88"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.65"
