api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "7c6cb48a109e65e7cf742e6805ab498152d39a3d3dcaa4da0ed081a6675d4dbb"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.65.tar.gz"
    source_sha256 = "d7d5c4327292c1fa2879481706ca196fb435d1a873bc244dac29884b43cee17a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.65-any-stack-7c6cb48a.tgz"
    version = "0.0.65"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "4c122f201a8f5359e7d9b3c0920a7a4cd8e9fe5e22bc6e95af9fb3f03a96d6ff"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.89.tar.gz"
    source_sha256 = "d49d00f425d27890c582f8a54a195bd3531513639d0c57d34a46c1e64ef8e59c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.89-any-stack-4c122f20.tgz"
    version = "0.0.89"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "739f9953fd03b5defce3300877593ea86b2791a79af984c44bfef10f0fbd87cf"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.72.tar.gz"
    source_sha256 = "6bbd22557e8de0715adcde789c3ef6742bec0f85b8fd0694c708a87e91379b0c"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.72-cflinuxfs3-739f9953.tgz"
    version = "0.0.72"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "1c065d5a9032bd72cbdef561bd62be4f085ab5ecf9fdd13b0eaf067332e60e31"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.91.tar.gz"
    source_sha256 = "0ced2dd29fa770a4fa9d5b9278e445d2deb9f5ff0e1edd597d6ac1b8dc9cd4d7"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.91-cflinuxfs3-1c065d5a.tgz"
    version = "0.0.91"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.91"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.72"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.89"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.65"
