api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "3b822cc963de07ab0b3788f4b8e925534f31ad5512deb924c8434bf6ea42d39d"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.71.tar.gz"
    source_sha256 = "4cff27a224446d8f7c92ae2751dae7cd9b59a12072f01a53dce04b1c857f2601"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.71-any-stack-3b822cc9.tgz"
    version = "0.0.71"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "6a3f6550aca2c7578c21bf90adbc3411ba006abc6ff94700cb21b471873e4b43"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.94.tar.gz"
    source_sha256 = "c5ccd073dc99bd1617ccdaf1477f6e2ce1c9bab97fe8ecfaec05746883bf5ef9"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.94-any-stack-6a3f6550.tgz"
    version = "0.0.94"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "09387926bc67e5560738f202ed0c641ae9ef59a22ba88009fee897891095154a"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.77.tar.gz"
    source_sha256 = "7635f9f1b9bf1f23afac3afc0bc2451f593e33d559d31c3e79401bb3755c8a58"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.77-cflinuxfs3-09387926.tgz"
    version = "0.0.77"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "07baa3fb0e87dd8953ddd3277906d344d4a8d7e801662a19b122627579540f25"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.97.tar.gz"
    source_sha256 = "86968cbb283dca43bbae3d0f341be02861d78ad7435f7657022afb0f302d48f7"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.97-cflinuxfs3-07baa3fb.tgz"
    version = "0.0.97"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.97"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.77"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.94"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.71"
