api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "31b552022352114e24e24b0a790889bb7a612fffed76a9da469756ea82414d67"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.37.tar.gz"
    source_sha256 = "0b0a82341896e9690de2c9d1f625bfed086fea3e7849a86f790e2e69daee1ed0"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.37-any-stack-31b55202.tgz"
    version = "0.0.37"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "cd7fdc30bb6d209b70ea9b62989f6217163fa0f39c70f679f93a75bd5767bee1"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.39.tar.gz"
    source_sha256 = "e7a125564ab9716c8667c36cb11f23b0fc291f7e05e612878bcc0f5b4ac8f0e2"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.39-any-stack-cd7fdc30.tgz"
    version = "0.0.39"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "cd7fdc30bb6d209b70ea9b62989f6217163fa0f39c70f679f93a75bd5767bee1"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.39.tar.gz"
    source_sha256 = "e7a125564ab9716c8667c36cb11f23b0fc291f7e05e612878bcc0f5b4ac8f0e2"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.39-any-stack-cd7fdc30.tgz"
    version = "0.0.39"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "e0c33ed3147d73205cd77b7eff3f9dbed5601f70d1d49c479a3f6762992e0d43"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.56.tar.gz"
    source_sha256 = "2507eb2bfcc4e87403d3822c75603762c8b06e411277b8b92440000202c00c14"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.56-any-stack-e0c33ed3.tgz"
    version = "0.0.56"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "5314b477ebbb9ab9a5e16067a0c102fc2c52c763aa936524c1b32947b0147d50"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.59.tar.gz"
    source_sha256 = "88c91596ac0df9ca411e130f32f0be58a8f93c381a9b3e068540c6ff9f19fce7"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.59-any-stack-5314b477.tgz"
    version = "0.0.59"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "5314b477ebbb9ab9a5e16067a0c102fc2c52c763aa936524c1b32947b0147d50"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.59.tar.gz"
    source_sha256 = "88c91596ac0df9ca411e130f32f0be58a8f93c381a9b3e068540c6ff9f19fce7"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.59-any-stack-5314b477.tgz"
    version = "0.0.59"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "5a95f48f7866623dc2cff2270f3dad14a1e7eb5b24bd6f8fad328784dc076acd"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.41.tar.gz"
    source_sha256 = "45d6b836a03a85200b938e10d4507a60c4041b9715e63d6576fc3681b68a083b"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.41-any-stack-5a95f48f.tgz"
    version = "0.0.41"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "cb4f60197551dde6406ccab2ce50fbe3a8a0561d0de8a8b7679e0f3356a93d19"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.44.tar.gz"
    source_sha256 = "b19a2cd1f96e60c4ebc8c186632b866c24348c0d063276723a296a229f84071f"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.44-any-stack-cb4f6019.tgz"
    version = "0.0.44"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "cb4f60197551dde6406ccab2ce50fbe3a8a0561d0de8a8b7679e0f3356a93d19"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.44.tar.gz"
    source_sha256 = "b19a2cd1f96e60c4ebc8c186632b866c24348c0d063276723a296a229f84071f"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.44-any-stack-cb4f6019.tgz"
    version = "0.0.44"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "e1cd806fbc03b5b9d29a3331afc3a6954c5affc8f02dd86996d21b673b828a2a"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.60.tar.gz"
    source_sha256 = "97503a69f1165b4b0df7b790e154923d97cb0b2ca9881a1ffaa7b9bf2da35938"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.60-any-stack-e1cd806f.tgz"
    version = "0.0.60"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "e1cd806fbc03b5b9d29a3331afc3a6954c5affc8f02dd86996d21b673b828a2a"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.60.tar.gz"
    source_sha256 = "97503a69f1165b4b0df7b790e154923d97cb0b2ca9881a1ffaa7b9bf2da35938"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.60-any-stack-e1cd806f.tgz"
    version = "0.0.60"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "e1cd806fbc03b5b9d29a3331afc3a6954c5affc8f02dd86996d21b673b828a2a"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.60.tar.gz"
    source_sha256 = "97503a69f1165b4b0df7b790e154923d97cb0b2ca9881a1ffaa7b9bf2da35938"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.60-any-stack-e1cd806f.tgz"
    version = "0.0.60"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.59"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.59"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.39"

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.39"

