api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "1b1e9ca2b0de9fba986835d57596d45266e4a9c9f42d1328554eac27e5d7cd51"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.23.tar.gz"
source_sha256 = "454c36470214c25f09099509727267eef2fe724e0d6a391b14ed469f6b183ef1"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.23-any-stack-1b1e9ca2.tgz"
version = "0.0.23"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "060fb6e6999e8a07e9dcc9aab46ae49a2ee53377d8b1eac08a18960edd3c2483"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.34.tar.gz"
source_sha256 = "7fd2d0e3ce9c3178a634dd6fedadf11b4140984325b7cf512b9858fc62643364"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.34-any-stack-060fb6e6.tgz"
version = "0.0.34"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "fa9ba1693c4c478bec471beab7f31f0bf8d38f001140635f78f6c6f6dd5e98e5"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.21.tar.gz"
source_sha256 = "eb969f5f99ed507997cac316602b1b2267d999a6dc28f11f4a4bfa5166deb420"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.21-any-stack-fa9ba169.tgz"
version = "0.0.21"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "65baf736d820983ddcfe229b2868cbabd6a5cc4320756d238a0abe10f329d7d9"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.33.tar.gz"
source_sha256 = "2fd8f7e50ab79f4a852939f4aa65b791caa2effe4375bceae5e641db0ae1e352"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.33-any-stack-65baf736.tgz"
version = "0.0.33"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.33"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.21"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.34"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.23"
