api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "7e7706f7edf85313461855c1233e60f4f1b43930128836b858c6ef6b2b4fd513"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.56.tar.gz"
    source_sha256 = "1ce936dc451b93d1ab016b1f9d927f6b82b613ad2f249c96f2ea95780e9479f7"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.56-any-stack-7e7706f7.tgz"
    version = "0.0.56"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "9e1c7631381d1f5c5a2000601c07e1f0c81c1c9b3cde71ba7014d818845fbd55"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.80.tar.gz"
    source_sha256 = "f83cb894ac502746979684e4cf6c8f2764ac2cdcefd55138eb6d87e33e7985be"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.80-any-stack-9e1c7631.tgz"
    version = "0.0.80"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "22de9e0741e0af03019aaf6a9d50a23f41f1eb251e6b0ddfca19f6cf3873b783"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.64.tar.gz"
    source_sha256 = "dbcd472cbfdffb81a397980e25c9cd9c88c644b93fe9f9d000d2fa0c3dee0669"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.64-any-stack-22de9e07.tgz"
    version = "0.0.64"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "40227ff62245bdbc5cf0f2e08190889bcc98cb53321245ebf155cf6191238328"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.83.tar.gz"
    source_sha256 = "a3e1f8efb2a5603045deb1688f518b6227265dc5bdce0f31e9d034692d34700d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.83-any-stack-40227ff6.tgz"
    version = "0.0.83"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.83"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.64"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.80"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.56"
