api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "5e21cd56e7cc8c2be845cf800967f5754bb171e135371f50f95afae63831cdb8"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.47.tar.gz"
    source_sha256 = "2f3bab709f87f89907035e2267ac225f721c781596b2e7305a856c1764c08232"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.47-any-stack-5e21cd56.tgz"
    version = "0.0.47"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "920433fec11f9b718abcef40d9480e227acaca07d15d39bf7f54d4ce7762e342"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.67.tar.gz"
    source_sha256 = "bed001ffc27aefcbeec1a7a44812741c2366ad1a06837cf4b488c600df33de0c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.67-any-stack-920433fe.tgz"
    version = "0.0.67"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "108915bc86ab492ec8bcfa200bfb814297f605c9a59ce9d0dbf337dc4d0f85e6"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.53.tar.gz"
    source_sha256 = "8a3a5796a7939e8f24076329f3314e97a4c37464789ff8b4be7fd46b2a816670"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.53-any-stack-108915bc.tgz"
    version = "0.0.53"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "6125f4f25a7c6cca1d29386c0757e1aaa00588978ac1056ef5d5f668befab2ff"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.67.tar.gz"
    source_sha256 = "ebba3a30fd754d84aefe9e04ee4b222538f941f97362e8ba9235c5c6074cedf5"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.67-any-stack-6125f4f2.tgz"
    version = "0.0.67"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.67"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.53"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.67"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.47"
