api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "4f5d991e8a6224dc72acfb7a8676f47fad77782590b08a5e7a9500b2385ac902"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.45.tar.gz"
    source_sha256 = "5fe5d7211b87de7d951701e781f64a85c9482e52e39a72b5871e27f436e494c4"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.45-any-stack-4f5d991e.tgz"
    version = "0.0.45"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "b53c418f6d68d5be210748f207a2f29258ff89bb289de136fe544691011a3b60"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.64.tar.gz"
    source_sha256 = "0ea00a865f4820d524f903805e4b401ec304e9e683ac368325c10a9c27775f9d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.64-any-stack-b53c418f.tgz"
    version = "0.0.64"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "b37dca8be4b8bb475a782978fd94e4feb9946eeda3824b6cb9d1f694fcb6738f"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.50.tar.gz"
    source_sha256 = "d570c82e587805ac2f98ca1cd68b4e9c34574d8a09f9a8ae58be0ffc95cef2ab"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.50-any-stack-b37dca8b.tgz"
    version = "0.0.50"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "1dd55ba962aad4466ef8dfecfe11347cd0eb36352c8bfb78ec145e29253ceb39"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.65.tar.gz"
    source_sha256 = "d5f058f867efdce97485aab986db713b308124e0ac0c86d01eb0d2bdf57c35a8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.65-any-stack-1dd55ba9.tgz"
    version = "0.0.65"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.65"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.50"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.64"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.45"
