api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "99b9f67101ef3195fb78c5da51e73ed0e80a26ace6059eadbf95fdc683298d57"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.27.tar.gz"
source_sha256 = "32fb411b5526605157802a0b4236c8d20073e568a263c5ca57d11f84de5162da"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.27-any-stack-99b9f671.tgz"
version = "0.0.27"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "d907c0147d16f66ba7f7744ac11283a2bb479edaf83e89289639e1b10fdb3318"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.37.tar.gz"
source_sha256 = "e7830758105e55656e9c93452695d381c66d34929d74589bfbe833e94a68d6ce"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.37-any-stack-d907c014.tgz"
version = "0.0.37"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "d0e21c842e34dc6c8fb408e8343ff4416d9ed3c4f8d9c2fd662c8c6a20b89b4d"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.25.tar.gz"
source_sha256 = "898f850e4642e8b12b547eb655c23706ef5ebc3d990897ca0aee32d4aef403aa"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.25-any-stack-d0e21c84.tgz"
version = "0.0.25"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "823dd9183968976929279f26cdba08cbf5bb606fbdf7077c9cda7d15bbb1f583"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.36.tar.gz"
source_sha256 = "5a918f9bde51396fe36af22e892519f9c3e909161aa4fed77c805ed83e750696"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.36-any-stack-823dd918.tgz"
version = "0.0.36"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.36"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.25"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.37"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.27"
