api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "68926fc575a8e3b7a27c8b8263ce4977e82386521183ce3461588fd13e818096"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.77.tar.gz"
    source_sha256 = "42ec42dac4603b249da8fd8dc645578f6feeb21094d84f1dd42214806f5e172a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.77-any-stack-68926fc5.tgz"
    version = "0.0.77"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "1b55b328804c2c8f468617958965d87ec0438e6854e5d825bd1ac34a6b7aefe0"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.100.tar.gz"
    source_sha256 = "b12701cc7643f2e7bd10e80b111381fe8045dfb3abd0355c88ada10eaa3decf1"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.100-any-stack-1b55b328.tgz"
    version = "0.0.100"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "af98bcfdbab5ba1d593d91aa362716d72cdb3056052b0984534ceb03aec61d30"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.83.tar.gz"
    source_sha256 = "d355e0af2c707ffcb8846f65382ead9f46c1bf9e10c4a6a9f570009affc1441d"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.83-cflinuxfs3-af98bcfd.tgz"
    version = "0.0.83"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "439470231bfd0519519826b35cd299c65f5c95eab81cce4e5ae1c62893d97a4e"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.105.tar.gz"
    source_sha256 = "ebd89cd1394d30ff38389e581333ec4d440f126bfca2ded006c609e7013fea2d"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.105-cflinuxfs3-43947023.tgz"
    version = "0.0.105"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.105"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.83"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.100"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.77"
