api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "d666b2664efa119192606a31bd681cdfbd38519e0012a21dd054c15b017dda5e"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.78.tar.gz"
    source_sha256 = "6fff9d4285a8e4dd08d528214d725e0bf6804225e2c40b3e39fab789e1960535"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.78-any-stack-d666b266.tgz"
    version = "0.0.78"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "598872b8dbc58b8642fc6054a74b60fa6d17134b1c6d77cb57cf30dbdf4682d5"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.101.tar.gz"
    source_sha256 = "318f9ca5e2fb8170534ac2398bf0953338909df02952081644e6b665fa0502ec"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.101-any-stack-598872b8.tgz"
    version = "0.0.101"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "af98bcfdbab5ba1d593d91aa362716d72cdb3056052b0984534ceb03aec61d30"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.83.tar.gz"
    source_sha256 = "d355e0af2c707ffcb8846f65382ead9f46c1bf9e10c4a6a9f570009affc1441d"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.83-cflinuxfs3-af98bcfd.tgz"
    version = "0.0.83"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "1e430bda0ec24ada45ac1f4fc8b55c434b3cd083acd87405e1bd65097a23dcf8"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.108.tar.gz"
    source_sha256 = "6c60ffc3df5a8dc0577fbba06faf756f18f32f814209725feb92b3816951ddbc"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.108-cflinuxfs3-1e430bda.tgz"
    version = "0.0.108"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.108"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.83"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.101"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.78"
