api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "c44bea87880c256a2f571ead75a2779decc48a51b46e168964b5fd7bc8f2a10b"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.26.tar.gz"
source_sha256 = "562606a933a4b62a7d2cb1558a580721bd0ed646fb0cae5596f1deeee1bc49bd"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.26-any-stack-c44bea87.tgz"
version = "0.0.26"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "9e6183eac8bbff83b53d0aaa898c6e4d6741535005687b854d2716327910ebe5"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.36.tar.gz"
source_sha256 = "acd6f248a1b959037bd1899e1cb1080c1ad033793360f25b04ae61fc195f646d"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.36-any-stack-9e6183ea.tgz"
version = "0.0.36"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "d0e21c842e34dc6c8fb408e8343ff4416d9ed3c4f8d9c2fd662c8c6a20b89b4d"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.25.tar.gz"
source_sha256 = "898f850e4642e8b12b547eb655c23706ef5ebc3d990897ca0aee32d4aef403aa"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.25-any-stack-d0e21c84.tgz"
version = "0.0.25"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "823dd9183968976929279f26cdba08cbf5bb606fbdf7077c9cda7d15bbb1f583"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.36.tar.gz"
source_sha256 = "5a918f9bde51396fe36af22e892519f9c3e909161aa4fed77c805ed83e750696"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.36-any-stack-823dd918.tgz"
version = "0.0.36"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.36"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.25"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.36"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.26"
