api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "9e5cb204874d8a5f89c4f11f1addfc79939c06f027534ce2c647fdb41643ac07"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.36.tar.gz"
source_sha256 = "d4f6d2fb2761b553b5fa38d41dc767a6cb9f8fecf9c9bf9408bc8099797b1b65"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.36-any-stack-9e5cb204.tgz"
version = "0.0.36"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "fd4c61915f18e2401d796fbcd673a05268ce029ece4de60bfd1d48ec097f5e7c"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.48.tar.gz"
source_sha256 = "5485a5411e6704d20d305a955b41767ac991532510e695e1ed53d9a5f1fe288b"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.48-any-stack-fd4c6191.tgz"
version = "0.0.48"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "cb1b278745d40cb6c63135e77549a0053abcc7b0904e81f830c1f9234ae9aadd"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.35.tar.gz"
source_sha256 = "1e138809532cc203738de8122e60239ed0b8cae8e4b6d232436df639f4035c8c"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.35-any-stack-cb1b2787.tgz"
version = "0.0.35"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "f18b5657a86b4a04627a2500eacd3b54b6f224d0ebe31fe0e597b8e53fe6ec7e"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.50.tar.gz"
source_sha256 = "f9c6e64db13864b6f8d754761cb08a68153b57ba98c753fc710db772cf1e7bda"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.50-any-stack-f18b5657.tgz"
version = "0.0.50"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.50"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.35"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.48"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.36"
