api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "4cd23fe7e487f003e754ecdf8bf7a21c14b0dc6b69713dea8e711d1a76c3e9fd"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.31.tar.gz"
source_sha256 = "bdaf003ade89c9b87d9c2f4cd727ee8321f22cab0e230b502510c2a247698c49"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.31-any-stack-4cd23fe7.tgz"
version = "0.0.31"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "ed0b5d751dc012bfdeff104ac11651ad23903a58e5e9748395d182e8f97202ac"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.42.tar.gz"
source_sha256 = "1efabdd55b2d969b09246ed2ed1957195c08f0eb965986bfeb390f900914b403"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.42-any-stack-ed0b5d75.tgz"
version = "0.0.42"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "d6008b8d36d052bfb45aafb14c12faa868ed87a46d1071a1f221edb133d0ccb4"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.28.tar.gz"
source_sha256 = "add23bfda5902f555d11b243a7f17c2d6457da9b404a8d867d4cf1e4ac4555ad"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.28-any-stack-d6008b8d.tgz"
version = "0.0.28"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "2ecfa76ab95f18686c42cc3352e04231b72bf422b9a3efb8968e48489e269865"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.40.tar.gz"
source_sha256 = "303da02da6b0f5009bb992e07845c3e187435fdc580d0844c39d2fd9c203f28d"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.40-any-stack-2ecfa76a.tgz"
version = "0.0.40"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.40"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.28"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.42"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.31"
