api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "8ca3e9d098e618d9bfc0f68096f16dc903a02575c05c61bf1711a416e3b11c3a"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.19.tar.gz"
source_sha256 = "5689edd84bf3f508e14a65a6555638bec51c42ceb045847b479bc6fe771dd172"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.19-any-stack-8ca3e9d0.tgz"
version = "0.0.19"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "9ef733b15e9fc370b2ef0a6687fca98ab496653b7147b6edd703f218b85a9727"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.28.tar.gz"
source_sha256 = "d884fb5f5840d66eda3e06fb15189a9ff36583db082b24190d6763c5c9c557a9"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.28-any-stack-9ef733b1.tgz"
version = "0.0.28"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "625ed09637de87cedbb5a89236caf002046f1417924de6c69e54f800d8953fc4"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.17.tar.gz"
source_sha256 = "dc455d313910656883903ca750a60f4a0c0a4bf85ad758cacb03211424df2373"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.17-any-stack-625ed096.tgz"
version = "0.0.17"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "f9135cba4439e7f571fea1e5cf5f815bba77d0a855a1780cd69760e72f41289d"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.26.tar.gz"
source_sha256 = "71a2feb83a30730ac4d5c2bb3969879a64c4c4065dc3da61d8a731b4ae66b5f8"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.26-any-stack-f9135cba.tgz"
version = "0.0.26"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.26"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.17"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.28"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.19"
