api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "44369e3fd1cbdafce2796e8b95970405029df3178317615ad7b2dbce0f7543d6"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.50.tar.gz"
    source_sha256 = "0f471705abe3f67bda7562011b151509fe6aa7515666d84ef538c4c8594aea6a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.50-any-stack-44369e3f.tgz"
    version = "0.0.50"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "f15f2e855e91c03675a0deeb0dfcd3616f3c2737f6bbe4ec02e03c63d39fa31a"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.71.tar.gz"
    source_sha256 = "d414243c2c155febbac35135a956e8bcba780f4580be6a50e68d3a322f90b7de"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.71-any-stack-f15f2e85.tgz"
    version = "0.0.71"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "665ab26ef09f101b4ccc8fd0ae7eb299ae9bba3f3940ab138d6eefe11c9072ed"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.57.tar.gz"
    source_sha256 = "f0341856d24dc2289f23ebcace6a45ff3e8069308240f4101abe46c0fb41d78f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.57-any-stack-665ab26e.tgz"
    version = "0.0.57"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "22186993bc302558897f9b83a14fd8e21f8410e7ba9221777be6888958403a33"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.72.tar.gz"
    source_sha256 = "c5b54d0c180001f529854e8ef2471d726c7876f402365c186073d6ed5bfb404e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.72-any-stack-22186993.tgz"
    version = "0.0.72"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.72"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.57"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.71"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.50"
