api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "a437883e35e34f7bc4cb14ec4a305bb4fa9369fc07a32a14e53815f3c3d0069c"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.30.tar.gz"
source_sha256 = "0cc019307258890390b933d5fdd3c6df2142d03076d8e25022a7e097a6a55d9a"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.30-any-stack-a437883e.tgz"
version = "0.0.30"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "8e1ae175e1ad200185f0ef4f34c3eac5e9eb5872deac54b7b643c02262e2d27a"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.40.tar.gz"
source_sha256 = "665377574acebaedae1bd74fb24069f06e22611288a0074c4f0c37a629095d1f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.40-any-stack-8e1ae175.tgz"
version = "0.0.40"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "98f2486dae8c41720ca429adb7af2b8b640019c6d74e0096abf7d18dd5acafb1"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.27.tar.gz"
source_sha256 = "ebced71d767cbbe4c63f995c849c5e11af456aa877d3389c7407c0bbb40cb8bd"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.27-any-stack-98f2486d.tgz"
version = "0.0.27"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "2ecfa76ab95f18686c42cc3352e04231b72bf422b9a3efb8968e48489e269865"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.40.tar.gz"
source_sha256 = "303da02da6b0f5009bb992e07845c3e187435fdc580d0844c39d2fd9c203f28d"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.40-any-stack-2ecfa76a.tgz"
version = "0.0.40"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.40"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.27"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.40"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.30"
