api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "fecb6db22cdafb97b3135477dba320547ffb3c2ce9371c381b2b1cd8bfd18286"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.24.tar.gz"
source_sha256 = "3237991a9a2daf4f44be815f487b570c4104cdd705fce49fcba3c107dd6909b2"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.24-any-stack-fecb6db2.tgz"
version = "0.0.24"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "060fb6e6999e8a07e9dcc9aab46ae49a2ee53377d8b1eac08a18960edd3c2483"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.34.tar.gz"
source_sha256 = "7fd2d0e3ce9c3178a634dd6fedadf11b4140984325b7cf512b9858fc62643364"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.34-any-stack-060fb6e6.tgz"
version = "0.0.34"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "3ff4e7d1d75733e8b1ffa328f5880e4958785e0132e030f6acc64c9cc036693a"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.22.tar.gz"
source_sha256 = "06503824759eb44f7c253e006ac62669ccdff0b8f1fa4501a95068bdbd4f06f6"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.22-any-stack-3ff4e7d1.tgz"
version = "0.0.22"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "65baf736d820983ddcfe229b2868cbabd6a5cc4320756d238a0abe10f329d7d9"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.33.tar.gz"
source_sha256 = "2fd8f7e50ab79f4a852939f4aa65b791caa2effe4375bceae5e641db0ae1e352"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.33-any-stack-65baf736.tgz"
version = "0.0.33"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.33"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.22"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.34"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.24"
