api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "6a6c08f212038699eaa61eecf37f54dc585e89a7b17030281854da6977482f79"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.33.tar.gz"
source_sha256 = "9579a46a3aea9daf3a3be87750992f60bade5ea1387910f07f9d5f92575db9c5"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.33-any-stack-6a6c08f2.tgz"
version = "0.0.33"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "f664d89182e46fa34dcf4c3ac061d60db253e2033e72d10d4c3980625f3a05d4"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.44.tar.gz"
source_sha256 = "6a35d77c488199d226cb3c51dc1fc1d7490c17624c261955f56b516a8f999fb8"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.44-any-stack-f664d891.tgz"
version = "0.0.44"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "91d193eba2d875ddd1ed73e11dc549cbf090fe8ccb40d04719389e474d4ee77f"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.29.tar.gz"
source_sha256 = "34652885130322eb3289c453badaaf7d54df201b4e61a8bdc37cc4a1254e52cc"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.29-any-stack-91d193eb.tgz"
version = "0.0.29"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "9772d7138d27018828dcf35e29bb61dc8e6ba6a5b43e8077ed72b36751c3f18b"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.43.tar.gz"
source_sha256 = "50f6a71289f007934c7db80075e0bbd12d444b3450e9527102a138f480f9bbea"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.43-any-stack-9772d713.tgz"
version = "0.0.43"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.43"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.29"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.44"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.33"
