api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "7e7706f7edf85313461855c1233e60f4f1b43930128836b858c6ef6b2b4fd513"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.56.tar.gz"
    source_sha256 = "1ce936dc451b93d1ab016b1f9d927f6b82b613ad2f249c96f2ea95780e9479f7"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.56-any-stack-7e7706f7.tgz"
    version = "0.0.56"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "534f999e5ad19340a5879bd70520f0d6e3add320310c7f6f9e831139896d68e4"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.79.tar.gz"
    source_sha256 = "d28713cee6bfd0c50b08dd6ea88e85c454fe2d4ee3852c4e09036196f04f6129"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.79-any-stack-534f999e.tgz"
    version = "0.0.79"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "22de9e0741e0af03019aaf6a9d50a23f41f1eb251e6b0ddfca19f6cf3873b783"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.64.tar.gz"
    source_sha256 = "dbcd472cbfdffb81a397980e25c9cd9c88c644b93fe9f9d000d2fa0c3dee0669"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.64-any-stack-22de9e07.tgz"
    version = "0.0.64"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "f32d676b450fde08387c2945c4ba1b720199e036088ad3316c72d37ec0d8e4a6"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.82.tar.gz"
    source_sha256 = "b66287f393964b1f4fa49237e5ae789f70dd496bc987826b40744814c4e0ae2c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.82-any-stack-f32d676b.tgz"
    version = "0.0.82"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.82"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.64"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.79"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.56"
