api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "e6e655470a69c2fcd25867f89593acdfee0d0cb126df8b5c5bf15bef103b60d6"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.25.tar.gz"
source_sha256 = "70cbb3c8d5f39bdfb15a39c094f0007f788a15613112ba68ddb0d79509c3af92"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.25-any-stack-e6e65547.tgz"
version = "0.0.25"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "9e6183eac8bbff83b53d0aaa898c6e4d6741535005687b854d2716327910ebe5"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.36.tar.gz"
source_sha256 = "acd6f248a1b959037bd1899e1cb1080c1ad033793360f25b04ae61fc195f646d"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.36-any-stack-9e6183ea.tgz"
version = "0.0.36"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "70d34da029fbf798024621a29eb2e23a3ccccf8480db3dd1ebb80e225012febb"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.24.tar.gz"
source_sha256 = "160d175f968353e2eafae22f676dd91c78d070d74315e601d5b5a0109d079ddf"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.24-any-stack-70d34da0.tgz"
version = "0.0.24"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "0736ed9642936e695bda951f6bd14900231fba4c4a51047d23206bd3c76fafbb"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.34.tar.gz"
source_sha256 = "06a07c03482cbf22ac3a0bfaa3760b4cef008af0354246ca4dec0f3974b5a84f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.34-any-stack-0736ed96.tgz"
version = "0.0.34"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.34"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.24"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.36"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.25"
