api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "b9a19111968cb618405eee636feb8188b11138f4e82a854c4631e7e6d49d0ef3"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.46.tar.gz"
    source_sha256 = "b775501de3d069b352e1a1574a5e300fe9b1486b690e88de0919a1e5ab74263e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.46-any-stack-b9a19111.tgz"
    version = "0.0.46"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "f7c9099f233676b549960046be7d276aad0a1d3c8f67f38464784814b9433478"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.65.tar.gz"
    source_sha256 = "72ac71fb05d93129f235ebd809b30cc372b38608bed77342e7ee95ba9867cdf0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.65-any-stack-f7c9099f.tgz"
    version = "0.0.65"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "3b9bb312890c918e41d9987c7949a285670a3872d657ab81ba1afc66cb9d23a7"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.51.tar.gz"
    source_sha256 = "3cdb080dbd2226e459f4718d2b6ba2fe0321363d484ca2437228cb0f508d3989"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.51-any-stack-3b9bb312.tgz"
    version = "0.0.51"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "932c49e9a1a56904169790f7bfaff1ca2cec0a5c13399a2b273f0827b42b3d0d"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.66.tar.gz"
    source_sha256 = "2f6d3dc8fe558bfab0201a846d30660310b4284bcf6dd0bb8c51ba92984d6c14"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.66-any-stack-932c49e9.tgz"
    version = "0.0.66"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.66"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.51"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.65"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.46"
