api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "92a247a0770665e0cc134d138932fbe1e1f9b704d5a3cf72db164f728aae048d"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.73.tar.gz"
    source_sha256 = "e7481d73ef85b488e4177109305de69bec8007ea503be7c9e56f71a92127a753"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.73-any-stack-92a247a0.tgz"
    version = "0.0.73"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "c5e8b4072d27578efe70c27d3303a5400854c296112d2fe15ba50f17436b45ea"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.96.tar.gz"
    source_sha256 = "1fd22c0209ce6118f453223b6282cb4f7ac2d85f7626a7b22cd249482bb335dd"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.96-any-stack-c5e8b407.tgz"
    version = "0.0.96"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "d9b7dccf40a5288ed7af69a27ce8420df73e8655bcf1e38889a6874c2762072d"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.79.tar.gz"
    source_sha256 = "97d59eb79a726f7f4ecfaea9bbd1924cf174d1cdc32c59d7431806df2c909e80"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.79-cflinuxfs3-d9b7dccf.tgz"
    version = "0.0.79"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "56c05e95ba3f83df45c6990d546b757423adc087b59bc686528a053c2b54f06f"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.100.tar.gz"
    source_sha256 = "a539bf1b64c6434f2e14a1aaab4c749e0df685bc6a0942a13eeb51af114aab74"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.100-cflinuxfs3-56c05e95.tgz"
    version = "0.0.100"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.100"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.79"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.96"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.73"
