api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "cc81959211f461cb7c2c041a4752b262bd02bfb99c346c08ffa1c9f2c9d1e8cf"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.53.tar.gz"
    source_sha256 = "d55fb1df6f934a5888211704807403cb1ed9cdfb59d3ef89ac0cf6ce9143738b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.53-any-stack-cc819592.tgz"
    version = "0.0.53"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "2343cdae28feb93bba42c6a685bf41ace272eac62625d46a3c5e8d4eb5064717"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.74.tar.gz"
    source_sha256 = "c163dd3eb1687e31534b5c40a003568efd7e74e1dc6893a95c0205c41ee62720"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.74-any-stack-2343cdae.tgz"
    version = "0.0.74"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "e9ff817149110e3da478a9f8d6ede5b5fdf58a126a0f1dbcc091ea6c557b7a30"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.60.tar.gz"
    source_sha256 = "328f6d3d2bd010b5cc8fc2ebfb3d0945c8badc6c286b361e69dad6b5f6536aa9"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.60-any-stack-e9ff8171.tgz"
    version = "0.0.60"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "f08e7530ef80166e82aa935ab20441c941e234cb633a53c306ff847f8e15305a"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.78.tar.gz"
    source_sha256 = "00ce6cbbb3a37a423350781b16c0a00eb4f8b9406da69549aaac1f0469ee4aa6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.78-any-stack-f08e7530.tgz"
    version = "0.0.78"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.78"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.60"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.74"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.53"
