api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "f745d16a7983c38e569547e7bac2ccb1e6ad3053131328ec80567e651a0feb0c"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.29.tar.gz"
source_sha256 = "956d8ac0df54b63f0c28fa336b2d95ad1aabb9da7cf871bc27e749aa9cbba8fb"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.29-any-stack-f745d16a.tgz"
version = "0.0.29"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "05a25d35f806065f9be4a981129e84a88b5f54ef16de8480bf6128a2e0107f6e"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.39.tar.gz"
source_sha256 = "9520d3000c15496279e5ac1675ebf6f344618506f27d72a9c9e6325ec8adda00"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.39-any-stack-05a25d35.tgz"
version = "0.0.39"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "98f2486dae8c41720ca429adb7af2b8b640019c6d74e0096abf7d18dd5acafb1"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.27.tar.gz"
source_sha256 = "ebced71d767cbbe4c63f995c849c5e11af456aa877d3389c7407c0bbb40cb8bd"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.27-any-stack-98f2486d.tgz"
version = "0.0.27"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "19f68aabce6f4149b00b19301db016a957508b953ef0d973f1f2be5962468809"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.37.tar.gz"
source_sha256 = "0e79e861a1881a5b1a193ca4e5bcad12551ec29359d040f221e868dfa66e2532"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.37-any-stack-19f68aab.tgz"
version = "0.0.37"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.37"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.27"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.39"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.29"
