api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "1b91014ee4ccf7b8001a9457cfd72ac32fa3bca557d01a27a6515ff65042b53e"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.44.tar.gz"
    source_sha256 = "ab9fc15c9650c17e1239ad83c702921b31d3902067f7816b6b89ac7e06982552"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.44-any-stack-1b91014e.tgz"
    version = "0.0.44"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "11e0c97c567594ac83f4eae61400a94ad7d78c49ba1c0d890233c297887367a6"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.63.tar.gz"
    source_sha256 = "35f39c4eb414d5530b171bca5c183a6a37ed93f2c2e66269d0ccc12fbae7e507"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.63-any-stack-11e0c97c.tgz"
    version = "0.0.63"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "a66dacffc5b833e6adfbe4e0dd51fff7d16cf31e46ae7b9b382e03da4f58c07e"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.49.tar.gz"
    source_sha256 = "086c780685f2961d17f859b38414f1123a0fcc7b05fd010c36aa33405813a88e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.49-any-stack-a66dacff.tgz"
    version = "0.0.49"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "ffb40e90ac2557bf59877a14de486aa73488a55c761a6f98d8b7b2849cba2935"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.64.tar.gz"
    source_sha256 = "d305f0a45f6f10ddd3a602bc095dcafa96a37923d4613a5df4618481a0865712"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.64-any-stack-ffb40e90.tgz"
    version = "0.0.64"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.64"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.49"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.63"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.44"
