api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "9e5cb204874d8a5f89c4f11f1addfc79939c06f027534ce2c647fdb41643ac07"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.36.tar.gz"
source_sha256 = "d4f6d2fb2761b553b5fa38d41dc767a6cb9f8fecf9c9bf9408bc8099797b1b65"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.36-any-stack-9e5cb204.tgz"
version = "0.0.36"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "0bf58079ef068b4ec880c6a8ec24422ab5110aa8a92a76cc184838baf1e2ee3f"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.47.tar.gz"
source_sha256 = "143e70a925e729ac13cebf6e5933c9d6d2708df512f90ca92298adb1ca4b176a"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.47-any-stack-0bf58079.tgz"
version = "0.0.47"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "31c9f0a2fc209a305e62b84eeeac457dcdaf08e2b7bc8f11e8d6117d90a4ab3e"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.32.tar.gz"
source_sha256 = "84b3290a0b8febac2fa59d4156e2d7c509719505bc15b4d2cf31a6af5df33901"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.32-any-stack-31c9f0a2.tgz"
version = "0.0.32"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "abfcf3a9efe7d562f139e3e91e8ed0228d55350dc1855d5b1fc09bd661a63280"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.48.tar.gz"
source_sha256 = "28ad2b2241d1ccde0168ceef301cfa33a46aaba764afc487a8ce11553d7edc86"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.48-any-stack-abfcf3a9.tgz"
version = "0.0.48"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.48"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.32"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.47"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.36"
