api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "8dad1a6c9e9b4fa56b7d8c20b46d154dab4df921383ea60c9b23c9c2b047b8df"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.35.tar.gz"
source_sha256 = "24b141493cbcb548d00713b4909b1f80e40eceaca0c26c0a53467aab44efcefc"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.35-any-stack-8dad1a6c.tgz"
version = "0.0.35"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "553e8285c0b32e02ae5645cad11da29614267b39f8a7bc75fffe56759495717d"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.45.tar.gz"
source_sha256 = "45d136df463d69e04235ff557647927904a0cd4b7d9e7e1be358e9891485a164"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.45-any-stack-553e8285.tgz"
version = "0.0.45"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "2fccdfe7a4696dc466ef524f91ea6e93afa1734fb4b0c608c845e1af60d7d2b5"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.31.tar.gz"
source_sha256 = "d80efb4cb58137f99ba89040c277265aa14c97e6f6ac51685c274643a23ca673"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.31-any-stack-2fccdfe7.tgz"
version = "0.0.31"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "0958b88b0d5ba8202627a1c8808f2799028e227732f3129d7da7f70bf0dd0754"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.46.tar.gz"
source_sha256 = "63a34a3006ccfb4058fa157c77f6dba249d6d6343a44d6e9726b2be2525439a9"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.46-any-stack-0958b88b.tgz"
version = "0.0.46"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.46"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.31"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.45"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.35"
