api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "6a6c08f212038699eaa61eecf37f54dc585e89a7b17030281854da6977482f79"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.33.tar.gz"
source_sha256 = "9579a46a3aea9daf3a3be87750992f60bade5ea1387910f07f9d5f92575db9c5"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.33-any-stack-6a6c08f2.tgz"
version = "0.0.33"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "efe94703983a3586fdee2f784834155c68d9d470b1ebdac328105fb19e4b6907"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.43.tar.gz"
source_sha256 = "2670ca163691bf0e581bdf688610dd1d13b16a1c5748cebaa8931ab246d8151e"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.43-any-stack-efe94703.tgz"
version = "0.0.43"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "91d193eba2d875ddd1ed73e11dc549cbf090fe8ccb40d04719389e474d4ee77f"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.29.tar.gz"
source_sha256 = "34652885130322eb3289c453badaaf7d54df201b4e61a8bdc37cc4a1254e52cc"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.29-any-stack-91d193eb.tgz"
version = "0.0.29"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "5378aa8f1849ce9bef6034394b5a800ae4fdae04442e72d87de5d04c973c5c6d"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.42.tar.gz"
source_sha256 = "13dc83f0d4c72fdd869723c2a0877328c5b0cc600d2efc60ee5239e9083c1597"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.42-any-stack-5378aa8f.tgz"
version = "0.0.42"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.42"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.29"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.43"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.33"
