api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "c55b66cf8c6af6f630f60fb6d46284b79226b1ad2cdbf9366080fa68e896b2ff"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.49.tar.gz"
    source_sha256 = "28ec431cc0bc703b0cbc06d2dda6f460f6872a2ae9015018edbedff27e9f32c0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.49-any-stack-c55b66cf.tgz"
    version = "0.0.49"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "1373e5aa7ebcf486982e0cbba9c4e9f5b6ef4719ff72a413edc41843ddd31c58"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.69.tar.gz"
    source_sha256 = "fd5c27bc0862ca2b99ac8bb198f1a374e0cb1e833f41e6226a1d20c9214c717d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.69-any-stack-1373e5aa.tgz"
    version = "0.0.69"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "5181873e981fecff97f5a8b294ae75c099749db5cfff2891154c8b52660aafe2"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.55.tar.gz"
    source_sha256 = "8c6c5a06344470e4e28d94adeb0f72e88df148de278bfbbc9b2b4bd86a4e31ba"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.55-any-stack-5181873e.tgz"
    version = "0.0.55"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "38d336d8fa5136788aa17b93ebfd114f52f0f793e9c11be3ef4c8a8aeb9ce1bd"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.70.tar.gz"
    source_sha256 = "060595e5b9682c020766c440d4a431b760c7c865241c970b4cf2cf269445374d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.70-any-stack-38d336d8.tgz"
    version = "0.0.70"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.70"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.55"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.69"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.49"
