api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "6dcc0c744b71c998a34367e08294588f0eed1d6c66109f78461031f0b4d54fd4"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "d26c05a1324a99684c68a19e5eb11ecd3a29d6be382b45f24fafc46635c5b97f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.68-any-stack-6dcc0c74.tgz"
    version = "0.0.68"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "fa60da5b3274c454b0e359c1d57770517e7593205d228bc1d9f7750cb93c3cc9"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.90.tar.gz"
    source_sha256 = "ae9805d36fb71c5d2d6ff4aa8a8ac676cdcd8606b3c9aac1d3a32d301d990e74"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.90-any-stack-fa60da5b.tgz"
    version = "0.0.90"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "f7b62d561bf07cc98c9daf358a73a2b8635558e3c955f8db02fb7b51ded22897"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.73.tar.gz"
    source_sha256 = "cf57a8b79658d7eb16acd64d6c8106e7e6b710b278ef03dfe0402c2643a352d9"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.73-cflinuxfs3-f7b62d56.tgz"
    version = "0.0.73"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "086fa1015fc76016dee8e38c96f9a8861e29f7c852b8ef263d7e40eced07beb5"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.94.tar.gz"
    source_sha256 = "9267ae9b546ca27853098e8e12454e6820331fbd8bd77205af0c5004d7971b5e"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.94-cflinuxfs3-086fa101.tgz"
    version = "0.0.94"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.94"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.73"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.90"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.68"
