api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "09062697e6d580b12cef0c6085edee2606d69ec66eef2a285f73b9c23b344aaf"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.80.tar.gz"
    source_sha256 = "67e3087f18e73f5c3437a214828d3d43a0584b7526a6169e069b21007ac54938"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda_0.0.80_linux_noarch_any-stack_09062697.tgz"
    version = "0.0.80"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "16cd4d8b6343f3a809b5fd2988c891cbd95f3ca353db0be48af0a1ebe4a10c54"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.105.tar.gz"
    source_sha256 = "c0233d3ada0d17360f2c83aebe0fc705932cd9ce0d0634c4f9e2132f5d1d0ce0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip_0.0.105_linux_noarch_any-stack_16cd4d8b.tgz"
    version = "0.0.105"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "4c0f8c178aeba0434b13df4d27d03e33ce2716e02f3c1337a7600f8d038732f7"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.86.tar.gz"
    source_sha256 = "e47d9cb876558e899d076895796a4fb7295fcb84aac00d775603a98e8df1305f"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv_0.0.86_linux_noarch_cflinuxfs3_4c0f8c17.tgz"
    version = "0.0.86"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "87cc1e5721cf4c295446f41522dcb23a7abd6545c3d99952ed2f564b91af52ef"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.110.tar.gz"
    source_sha256 = "b21d7c496c71bf617ae5544976eef9106a886a4dfdcab6fd197b23f0e15a028b"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.110-cflinuxfs3-87cc1e57.tgz"
    version = "0.0.110"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.110"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.86"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.105"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.80"
