api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "f8d1505ea42f35c2ee211ea84aae75cd04b10783252548bd1846f76637b0aa92"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.20.tar.gz"
source_sha256 = "94c773335288eaa7c39c60fef6f2d996fc55f5fd128b49f9a517129487dbb4fe"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.20-any-stack-f8d1505e.tgz"
version = "0.0.20"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "ef2da213a8a48dbcc205c94538cfac7fd65a2be1f8b2ca5733a39b4639b4382c"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.29.tar.gz"
source_sha256 = "abaca5b90e0acbcd9968d388a8be27e1ca0e9d5bfc10ed4ff6e4369004f6af54"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.29-any-stack-ef2da213.tgz"
version = "0.0.29"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "3da13dd57ecac506620005124b70006b76d92276d7637727d4bd6f7f2267e753"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.19.tar.gz"
source_sha256 = "fb5c718b4194236879a597178b7a07956c544d3fa685592abf9362c97ff26c49"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.19-any-stack-3da13dd5.tgz"
version = "0.0.19"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "277c60c3514bc9640ca687f9ea499a0732cc1c1fc43ee7ffc4db27135c07e926"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.29.tar.gz"
source_sha256 = "2e6a47bd7cd82b554915ed9efc0b75e0dd454e6a76160d39aec0c1b824989154"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.29-any-stack-277c60c3.tgz"
version = "0.0.29"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.29"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.19"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.29"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.20"
