api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "40ce60cdae789ac9525f26aac1c8ae98c1353f255867870849d0a5a8fc294ced"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.51.tar.gz"
    source_sha256 = "b0f733765c0217475d3be184cfbaf6d825ac48881113b5c73324c539877228a9"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.51-any-stack-40ce60cd.tgz"
    version = "0.0.51"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "b5bbd59afd130c4275fde2d04edf2738e9acd1adab0efc1ae573d9b4f6c7f5d3"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.73.tar.gz"
    source_sha256 = "bcfa3f83cc02077c0f644ffae41c5c1950c296766f73d808362f7ab668cbfaa1"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.73-any-stack-b5bbd59a.tgz"
    version = "0.0.73"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "9a70b0e987bed7c713c485512efaa35e4de6ad8ffd0489bccb4bd082f6ed4267"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.59.tar.gz"
    source_sha256 = "74d3ec1a42e18b4cccdea665d1015394e9b4f1ac41fb1c149ff73f4f63106fb2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.59-any-stack-9a70b0e9.tgz"
    version = "0.0.59"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "74c6f84ee57263f63f9659e1c3cf64102c23eb87a79f3fbf5100f9ff5597625a"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.74.tar.gz"
    source_sha256 = "9c2c8bbfe695eb1671378ccf65d4309606f61b3b008db42deb521c1bcbd96b7d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.74-any-stack-74c6f84e.tgz"
    version = "0.0.74"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.74"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.59"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.73"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.51"
