api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "6a61ce69d800e2377b3c2c7c92382a549131957cf963ba58f7e1be00cde92f2e"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.48.tar.gz"
    source_sha256 = "1f7605539e017f22ce43ed8c5a8f4271460432c1c1b56e744fe0b65d1a1e3e24"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.48-any-stack-6a61ce69.tgz"
    version = "0.0.48"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "b7b04e266ee4702b289350e443b7b930f1c9d3b08ad1b983062e20928eb940ab"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "f47426e3eeefa3af51efeb0d16b7c44534e648d9e7d5bc762e8c761634e5bae8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.68-any-stack-b7b04e26.tgz"
    version = "0.0.68"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "79aeac4dcbbeede35ba0744ca94a15922e90930e4926dd43129af7343cd30aca"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.54.tar.gz"
    source_sha256 = "87f3c888b7acf551d46fc7355c908498621fd5047fc8e8dd4943c1ac9b52e328"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.54-any-stack-79aeac4d.tgz"
    version = "0.0.54"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "6512349d0ec0ae760cc0485ddad05336610c6eec8d4d155ab4bedff24cdce8d7"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "684ec25a3200b1c86fc9895b20a3e2e40b60ba55d593f777e729a7e7c47ca79f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.68-any-stack-6512349d.tgz"
    version = "0.0.68"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.68"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.54"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.68"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.48"
