api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "8f155d149c6b038488524efb1badbc27dd0ee982d1c3c58f9c39cb8938224359"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.55.tar.gz"
    source_sha256 = "ccad248efdb7fb6ab9a9c63a7ee98a7482218db7b5b0897892856e178c2bb9a5"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.55-any-stack-8f155d14.tgz"
    version = "0.0.55"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "534f999e5ad19340a5879bd70520f0d6e3add320310c7f6f9e831139896d68e4"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.79.tar.gz"
    source_sha256 = "d28713cee6bfd0c50b08dd6ea88e85c454fe2d4ee3852c4e09036196f04f6129"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.79-any-stack-534f999e.tgz"
    version = "0.0.79"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "c9f4fc08cafdddaab6f251a7664e7215c3ff6eef19aa404667fcf671ce1388d1"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.63.tar.gz"
    source_sha256 = "5a6777d99f3ad40a3853b0425309a31c9028a6d414c8a92727eb5748a4e80289"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.63-any-stack-c9f4fc08.tgz"
    version = "0.0.63"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "1bb969a4e30b0c44662c6cd50f5a0c58c0401eba5909447e779d0ae8abd45949"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.81.tar.gz"
    source_sha256 = "9b924befe8d535ac4dc4d7471fc7bd4c81bd2062534c02f5dc944e51b2d50666"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.81-any-stack-1bb969a4.tgz"
    version = "0.0.81"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.81"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.63"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.79"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.55"
