api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "b89013cc9a5ff4b73cbcf7e2413f91f69f18e4fc302514dac17fb0bd3522e62b"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.70.tar.gz"
    source_sha256 = "e80d2a332b5baf0e5977b01e267a301128f5e098f47088d057204e2daa300da1"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.70-any-stack-b89013cc.tgz"
    version = "0.0.70"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "389d5e39af974939501a201a1895e1b0f52e309b73a40991683f6bb8fdeec36d"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.91.tar.gz"
    source_sha256 = "fc670fccf8e0f7c2ffe9608e9f8f28460db9ddb15338d2a0c54262bfd2908131"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.91-any-stack-389d5e39.tgz"
    version = "0.0.91"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "09387926bc67e5560738f202ed0c641ae9ef59a22ba88009fee897891095154a"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.77.tar.gz"
    source_sha256 = "7635f9f1b9bf1f23afac3afc0bc2451f593e33d559d31c3e79401bb3755c8a58"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.77-cflinuxfs3-09387926.tgz"
    version = "0.0.77"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "07baa3fb0e87dd8953ddd3277906d344d4a8d7e801662a19b122627579540f25"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.97.tar.gz"
    source_sha256 = "86968cbb283dca43bbae3d0f341be02861d78ad7435f7657022afb0f302d48f7"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.97-cflinuxfs3-07baa3fb.tgz"
    version = "0.0.97"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.97"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.77"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.91"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.70"
