api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "fe0d7d00c6845aa7fa5d7642037fd5751163d9cecddd25138d696a96168f170d"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.79.tar.gz"
    source_sha256 = "2c2210a912f988b038b042665de86e9d5ed68a79ecc31d3dea5de61f6c772bb9"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.79-any-stack-fe0d7d00.tgz"
    version = "0.0.79"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "743f3369dd7450d6412b10a70663ec214c584861c29842acea4d6bfbf227957a"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.102.tar.gz"
    source_sha256 = "eaee60f10a25435c17526c1fc9ab58f8a3a99173fe52b571e1c01c2879e831b3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.102-any-stack-743f3369.tgz"
    version = "0.0.102"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "e4975db4b332de0a5681204e6a4521bc0d7a56b4f55b3a4ce1359d3c79648400"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.84.tar.gz"
    source_sha256 = "6b72e085aef47a7da7ea14ef243b500ecd9abbfe8bd3113e6fac0009a16f798a"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.84-cflinuxfs3-e4975db4.tgz"
    version = "0.0.84"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "87cc1e5721cf4c295446f41522dcb23a7abd6545c3d99952ed2f564b91af52ef"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.110.tar.gz"
    source_sha256 = "b21d7c496c71bf617ae5544976eef9106a886a4dfdcab6fd197b23f0e15a028b"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.110-cflinuxfs3-87cc1e57.tgz"
    version = "0.0.110"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.110"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.84"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.102"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.79"
