api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "9e5cb204874d8a5f89c4f11f1addfc79939c06f027534ce2c647fdb41643ac07"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.36.tar.gz"
source_sha256 = "d4f6d2fb2761b553b5fa38d41dc767a6cb9f8fecf9c9bf9408bc8099797b1b65"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.36-any-stack-9e5cb204.tgz"
version = "0.0.36"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "49d54220ba1839de773194940efd1ba01adbbccecce35111d0d73865736b8c0e"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.50.tar.gz"
source_sha256 = "59e61d3eb5c3390bac93d650549d6d722274e5455fc8519a4326bb145f4e5438"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.50-any-stack-49d54220.tgz"
version = "0.0.50"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "cb1b278745d40cb6c63135e77549a0053abcc7b0904e81f830c1f9234ae9aadd"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.35.tar.gz"
source_sha256 = "1e138809532cc203738de8122e60239ed0b8cae8e4b6d232436df639f4035c8c"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.35-any-stack-cb1b2787.tgz"
version = "0.0.35"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "0960e53ed817bc58dd6e885af9c72057dca1b42a6097461ceea7a92f09f9055c"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.51.tar.gz"
source_sha256 = "5c6057de4fe7b6fce2646fb068b9a9cf02bd2021cf20fcbe3631b97d2d9154d9"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.51-any-stack-0960e53e.tgz"
version = "0.0.51"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.51"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.35"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.50"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.36"
