api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "82a96c1022c127072b651665cf73de43e598866918c9c9adbb8546dcac7ff33d"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.61.tar.gz"
    source_sha256 = "c3e40d08124f2b7dd9d08f1ac2b6b6da49cd6a14b2d08d566c216f91f8ec3564"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.61-any-stack-82a96c10.tgz"
    version = "0.0.61"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "1064a0eab32e755e409656a4b68b783d6b08a50c9d567eee6ca52af6e83b4a87"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.83.tar.gz"
    source_sha256 = "f7e327756a59f3b1f71382c82e1d9ce0ec6843d21cc575519141e35cbd117cdc"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.83-any-stack-1064a0ea.tgz"
    version = "0.0.83"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "7a4a56ef313a9fbb0831b9f833673fbbe9774b878c4ef24e355726cad9ffbb4c"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.69.tar.gz"
    source_sha256 = "e904ac713f32765b76885f5c0ceaeaacf66f4a1d89f78434adaf61e373517549"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.69-any-stack-7a4a56ef.tgz"
    version = "0.0.69"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "200e1079ff6febe982af9502399eb7695f5a18226d73306172494ccc5cbeeb86"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.87.tar.gz"
    source_sha256 = "57c0ef8150e9ffd9062f41004bc8369249752a934be27b357d331dce22da4257"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.87-any-stack-200e1079.tgz"
    version = "0.0.87"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.87"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.69"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.83"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.61"
