api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "44369e3fd1cbdafce2796e8b95970405029df3178317615ad7b2dbce0f7543d6"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.50.tar.gz"
    source_sha256 = "0f471705abe3f67bda7562011b151509fe6aa7515666d84ef538c4c8594aea6a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.50-any-stack-44369e3f.tgz"
    version = "0.0.50"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "f15f2e855e91c03675a0deeb0dfcd3616f3c2737f6bbe4ec02e03c63d39fa31a"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.71.tar.gz"
    source_sha256 = "d414243c2c155febbac35135a956e8bcba780f4580be6a50e68d3a322f90b7de"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.71-any-stack-f15f2e85.tgz"
    version = "0.0.71"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "bdcc307ef8a3ad427a51b23bba24199a986a4c2e693c091bef11b163422a3801"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.58.tar.gz"
    source_sha256 = "42b5a870c9d2370fca1bd8b549f03201916aeb155e4c84553c9db9d538ae30fe"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.58-any-stack-bdcc307e.tgz"
    version = "0.0.58"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "71e53fff0a6b2b2c158fcba8b3ad3a9947fe25223639738f6bb59d95c5f6678f"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.73.tar.gz"
    source_sha256 = "51051fa94b05ec35b2bb5008fe15172a18c43390c3bd1c597c15c13e7531be22"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.73-any-stack-71e53fff.tgz"
    version = "0.0.73"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.73"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.58"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.71"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.50"
