api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "9c31969cff0e3a94b43a8759bba50128992490e9a42dd96e1eeb4b1e3375ebf1"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.76.tar.gz"
    source_sha256 = "b73638f66ed7de872ec3cf38cd62b8871293ddaccdedfeec1e0a3cfdac687674"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.76-any-stack-9c31969c.tgz"
    version = "0.0.76"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "b7893efcc192e2a57e97577454cd392deccffea3691f70a98c3c247df8479da5"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.98.tar.gz"
    source_sha256 = "81ed3e90a3b166ad73eac4092420ef319e72b13b8dae9ed86f4df6062f758a6c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.98-any-stack-b7893efc.tgz"
    version = "0.0.98"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "94f3c27b95cead7c65dfd5a5eecdaf2cc4b4e16b2b1c95536c8214009c7db9c5"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.81.tar.gz"
    source_sha256 = "93089ac97c0309c96d22d5d68409b733b3b298ba48beec91e3acc7ed695c07ee"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.81-cflinuxfs3-94f3c27b.tgz"
    version = "0.0.81"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "85e856506510361462545411b8fdad502f474ff504a98341dc742d78ec42e7a9"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.103.tar.gz"
    source_sha256 = "533cf0db685c6a2d273b9e27865181643796bdb28b49769fd7e8598bb4859517"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.103-cflinuxfs3-85e85650.tgz"
    version = "0.0.103"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.103"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.81"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.98"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.76"
