api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "ed028433db5d6199fa59f858babeb7934a8b5429f72a7d9a62d31cb1d9f0480e"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.75.tar.gz"
    source_sha256 = "c185d11149d03bef9b1163a07dc627b3ad64c20cb956b6e7a3d587e5182ff9af"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.75-any-stack-ed028433.tgz"
    version = "0.0.75"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "57aa01c496f65dbeb1e4a75b486636eaaf99b2380b44d55745f9a79ad62244a9"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.97.tar.gz"
    source_sha256 = "e985587478acb0f65afdf75649d266f3c8f22edd419de8edff281fd6a5a81dca"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.97-any-stack-57aa01c4.tgz"
    version = "0.0.97"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "d9b7dccf40a5288ed7af69a27ce8420df73e8655bcf1e38889a6874c2762072d"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.79.tar.gz"
    source_sha256 = "97d59eb79a726f7f4ecfaea9bbd1924cf174d1cdc32c59d7431806df2c909e80"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.79-cflinuxfs3-d9b7dccf.tgz"
    version = "0.0.79"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "38d63acb7efbf8953469cd8e08f16135a40ef1051a094f8b5c85cf6aee20c5b5"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.101.tar.gz"
    source_sha256 = "b0c89f1d65c236bf8281905210d9ee95d1fd629acbd7f5835e14a887dfaeeb8c"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.101-cflinuxfs3-38d63acb.tgz"
    version = "0.0.101"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.101"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.79"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.97"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.75"
