api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "9ebc1e6bb98e07ddec118b9ff85ebe64d2f9a3ae36793eb7966891867a4bc551"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.59.tar.gz"
    source_sha256 = "db35c6e6d4a463bfc621207d09f53c86dc16bc75cedc6ac747c9dc71756ee268"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.59-any-stack-9ebc1e6b.tgz"
    version = "0.0.59"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "1064a0eab32e755e409656a4b68b783d6b08a50c9d567eee6ca52af6e83b4a87"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.83.tar.gz"
    source_sha256 = "f7e327756a59f3b1f71382c82e1d9ce0ec6843d21cc575519141e35cbd117cdc"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.83-any-stack-1064a0ea.tgz"
    version = "0.0.83"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "8843d04e766cd5d0c80f83eed5107a00876acfbd570354b7a942bc4fb63e15b7"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.67.tar.gz"
    source_sha256 = "a7004f4893767933654c19dab62c00e7d20839580276ec497c74af547f72c84c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.67-any-stack-8843d04e.tgz"
    version = "0.0.67"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "c0c9231611ff59b76c955351037fb9acfaecc5bc10073fd8950513dc179fbf65"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.86.tar.gz"
    source_sha256 = "761951e26405088cc276162d7b0223c904da7ff8b724acb89acfa1fcc1f3159e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.86-any-stack-c0c92316.tgz"
    version = "0.0.86"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.86"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.67"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.83"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.59"
