api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "ed028433db5d6199fa59f858babeb7934a8b5429f72a7d9a62d31cb1d9f0480e"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.75.tar.gz"
    source_sha256 = "c185d11149d03bef9b1163a07dc627b3ad64c20cb956b6e7a3d587e5182ff9af"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.75-any-stack-ed028433.tgz"
    version = "0.0.75"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "b7893efcc192e2a57e97577454cd392deccffea3691f70a98c3c247df8479da5"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.98.tar.gz"
    source_sha256 = "81ed3e90a3b166ad73eac4092420ef319e72b13b8dae9ed86f4df6062f758a6c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.98-any-stack-b7893efc.tgz"
    version = "0.0.98"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "2903876f8d64d74a2fd056d947c94598bc13ad99bf6a7308f3cc358525854e48"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.80.tar.gz"
    source_sha256 = "acc59fab0eed5ea126596fd777d170f5cad682b5fccab92fad573dc688f34824"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.80-cflinuxfs3-2903876f.tgz"
    version = "0.0.80"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "8206a391bd45c47e3990c86756798893b3c5dbb6265e7c4a9cec9d715fa458f4"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.102.tar.gz"
    source_sha256 = "cb16d580b7032bbd7aea6b349c0ad82351db4f2f2837ab0e9aa41865120c8c3e"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.102-cflinuxfs3-8206a391.tgz"
    version = "0.0.102"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.102"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.80"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.98"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.75"
