api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "91a8bcae25a1706de65cb08e2d95b55adf79e17940635ad0326adba29a0c5b51"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.32.tar.gz"
source_sha256 = "c7d6d18090a60bd2442c37371b3f908e485463f071a9aba79f18832d16746188"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.32-any-stack-91a8bcae.tgz"
version = "0.0.32"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "efe94703983a3586fdee2f784834155c68d9d470b1ebdac328105fb19e4b6907"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.43.tar.gz"
source_sha256 = "2670ca163691bf0e581bdf688610dd1d13b16a1c5748cebaa8931ab246d8151e"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.43-any-stack-efe94703.tgz"
version = "0.0.43"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "91d193eba2d875ddd1ed73e11dc549cbf090fe8ccb40d04719389e474d4ee77f"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.29.tar.gz"
source_sha256 = "34652885130322eb3289c453badaaf7d54df201b4e61a8bdc37cc4a1254e52cc"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.29-any-stack-91d193eb.tgz"
version = "0.0.29"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "69642707b75dec494cde6443b0f01dfc75ce0a4fd6682bcbcbd6d87e4d4da08b"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.41.tar.gz"
source_sha256 = "dd31ea41c91b48d9f8b4e533440a849e2ff3d5159430298b2111dd9ec7b06b7b"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.41-any-stack-69642707.tgz"
version = "0.0.41"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.41"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.29"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.43"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.32"
