api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "4f5d991e8a6224dc72acfb7a8676f47fad77782590b08a5e7a9500b2385ac902"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.45.tar.gz"
    source_sha256 = "5fe5d7211b87de7d951701e781f64a85c9482e52e39a72b5871e27f436e494c4"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.45-any-stack-4f5d991e.tgz"
    version = "0.0.45"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "b53c418f6d68d5be210748f207a2f29258ff89bb289de136fe544691011a3b60"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.64.tar.gz"
    source_sha256 = "0ea00a865f4820d524f903805e4b401ec304e9e683ac368325c10a9c27775f9d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.64-any-stack-b53c418f.tgz"
    version = "0.0.64"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "3b9bb312890c918e41d9987c7949a285670a3872d657ab81ba1afc66cb9d23a7"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.51.tar.gz"
    source_sha256 = "3cdb080dbd2226e459f4718d2b6ba2fe0321363d484ca2437228cb0f508d3989"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.51-any-stack-3b9bb312.tgz"
    version = "0.0.51"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "932c49e9a1a56904169790f7bfaff1ca2cec0a5c13399a2b273f0827b42b3d0d"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.66.tar.gz"
    source_sha256 = "2f6d3dc8fe558bfab0201a846d30660310b4284bcf6dd0bb8c51ba92984d6c14"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.66-any-stack-932c49e9.tgz"
    version = "0.0.66"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.66"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.51"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.64"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.45"
