api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "b9a19111968cb618405eee636feb8188b11138f4e82a854c4631e7e6d49d0ef3"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.46.tar.gz"
    source_sha256 = "b775501de3d069b352e1a1574a5e300fe9b1486b690e88de0919a1e5ab74263e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.46-any-stack-b9a19111.tgz"
    version = "0.0.46"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "7f2edb0f68d780402d6af100d52887fc0d694e1f1c09232bd922cacef5a20796"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.66.tar.gz"
    source_sha256 = "bc3bffac1bfccb69f564c5f00819adb8cddab65fca8a782e880b3a43bf40aa4c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.66-any-stack-7f2edb0f.tgz"
    version = "0.0.66"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "3b9bb312890c918e41d9987c7949a285670a3872d657ab81ba1afc66cb9d23a7"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.51.tar.gz"
    source_sha256 = "3cdb080dbd2226e459f4718d2b6ba2fe0321363d484ca2437228cb0f508d3989"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.51-any-stack-3b9bb312.tgz"
    version = "0.0.51"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "6125f4f25a7c6cca1d29386c0757e1aaa00588978ac1056ef5d5f668befab2ff"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.67.tar.gz"
    source_sha256 = "ebba3a30fd754d84aefe9e04ee4b222538f941f97362e8ba9235c5c6074cedf5"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.67-any-stack-6125f4f2.tgz"
    version = "0.0.67"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.67"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.51"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.66"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.46"
