api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "fecb6db22cdafb97b3135477dba320547ffb3c2ce9371c381b2b1cd8bfd18286"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.24.tar.gz"
source_sha256 = "3237991a9a2daf4f44be815f487b570c4104cdd705fce49fcba3c107dd6909b2"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.24-any-stack-fecb6db2.tgz"
version = "0.0.24"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "575aa290994fd528b968c4784a10a0ebf0fb5f0b381226ff3f0176b74f1e76a8"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.35.tar.gz"
source_sha256 = "71ff5b2f1793b181abf5aead0e12bc9b9b4feb458c0ea52fa45d633769bb01b9"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.35-any-stack-575aa290.tgz"
version = "0.0.35"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "c01487624a7bc5ae0b75172312e37af304c2b259eb76b8419b09af3256d66016"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.23.tar.gz"
source_sha256 = "11c286c7c8e419afe0ecf9763dfa9d87bf598e10ca5d321c526dabe407864899"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.23-any-stack-c0148762.tgz"
version = "0.0.23"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "0736ed9642936e695bda951f6bd14900231fba4c4a51047d23206bd3c76fafbb"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.34.tar.gz"
source_sha256 = "06a07c03482cbf22ac3a0bfaa3760b4cef008af0354246ca4dec0f3974b5a84f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.34-any-stack-0736ed96.tgz"
version = "0.0.34"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.34"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.23"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.35"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.24"
