api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "6409ed204b9a465dfb20308d39c7b77bb8234991f08d55f2bbc0b43acbf3a82f"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.64.tar.gz"
    source_sha256 = "6aef8c87389b06c0f4443129c12896ce2b7f6a53dfef0a17ab26ee2c42790fee"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.64-any-stack-6409ed20.tgz"
    version = "0.0.64"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "785c6a614d3c4fee3a1bee676339f2ec64051708967905fe151c7d7a5fd7df92"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.88.tar.gz"
    source_sha256 = "eb7341fe47fc6e7a47d64467a4788d12aa4389d494bda30608dc28e13a18b51f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.88-any-stack-785c6a61.tgz"
    version = "0.0.88"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "243efedc69244a655b0714f04c4a5465d823cbf235f3e880a5c3c6b862669d21"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.71.tar.gz"
    source_sha256 = "d83db60625febdd28e4fa5782ae55224a33ec84210c828734ff0e774fdf441da"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.71-any-stack-243efedc.tgz"
    version = "0.0.71"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "04e8ecfe2729e385c06854a30bb7c3f99964bf4c009ecf101823396f0ea160b3"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.89.tar.gz"
    source_sha256 = "bbdea455632a6f8eee0ad43075ed5e8fd1ec91e641ab7fefdd7032f2c8e0e656"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.89-any-stack-04e8ecfe.tgz"
    version = "0.0.89"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.89"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.71"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.88"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.64"
