api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "72b856a132755f61ef8e0c8d972e2a4f3b067033defbd5851e17d655d82bdbce"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.72.tar.gz"
    source_sha256 = "6b538501292ede3f4a0234abe9b8dea1b1159eff3a571e1e1cbf0800e5e80385"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.72-any-stack-72b856a1.tgz"
    version = "0.0.72"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "08bf21fa01d0bbefb0322cf366b922d97008ea749f329a705ec8ac40dd7ab966"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.95.tar.gz"
    source_sha256 = "c33fc5c7b3266337f2b464586a6bc4a2b406d151818159a05931626fe2de1152"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.95-any-stack-08bf21fa.tgz"
    version = "0.0.95"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "15b9781bd50cd48897d27aed45b55b1a4e95968b55eee83838dd594c598e2da6"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.78.tar.gz"
    source_sha256 = "efa8d766636f42718a13651d3b37949d7a7559dd1fd53be5fa11388383c501f0"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.78-cflinuxfs3-15b9781b.tgz"
    version = "0.0.78"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "41f12d30e57204926639e7508e3928f1aeb36697f2db77f4f0c30509471e8da9"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.98.tar.gz"
    source_sha256 = "809352128b1f714160cee048e5597ebf4a6c4eeafb75a3fdbde0b2a690eff89a"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.98-cflinuxfs3-41f12d30.tgz"
    version = "0.0.98"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.98"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.78"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.95"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.72"
