api = "0.2"

[buildpack]
id = "org.cloudfoundry.python"
name = "Python Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.conda"
sha256 = "3e105c4396eec0f61c0d7f0365196e1c1a896de50e0e6812c72af51176723e9d"
source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.17.tar.gz"
source_sha256 = "7fd806aaa4f7605c5efaf73a576e2290f4d23c87ab62e8bf69dffd5ae4ab65ce"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.17-any-stack-3e105c43.tgz"
version = "0.0.17"

[[metadata.dependencies]]
id = "org.cloudfoundry.pip"
sha256 = "23c75097e05a80835657e2f0962b904522793d7d49bbe41d98cf075ab77a6326"
source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.25.tar.gz"
source_sha256 = "75d37fe501d543bfb472d9b0508e054b21a12af4923e6146e7e82ff9d8be96da"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.25-any-stack-23c75097.tgz"
version = "0.0.25"

[[metadata.dependencies]]
id = "org.cloudfoundry.pipenv"
sha256 = "625ed09637de87cedbb5a89236caf002046f1417924de6c69e54f800d8953fc4"
source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.17.tar.gz"
source_sha256 = "dc455d313910656883903ca750a60f4a0c0a4bf85ad758cacb03211424df2373"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.17-any-stack-625ed096.tgz"
version = "0.0.17"

[[metadata.dependencies]]
id = "org.cloudfoundry.python-runtime"
sha256 = "f9135cba4439e7f571fea1e5cf5f815bba77d0a855a1780cd69760e72f41289d"
source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.26.tar.gz"
source_sha256 = "71a2feb83a30730ac4d5c2bb3969879a64c4c4065dc3da61d8a731b4ae66b5f8"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.26-any-stack-f9135cba.tgz"
version = "0.0.26"

[[order]]

[[order.group]]
id = "org.cloudfoundry.python-runtime"
version = "0.0.26"

[[order.group]]
id = "org.cloudfoundry.pipenv"
optional = true
version = "0.0.17"

[[order.group]]
id = "org.cloudfoundry.pip"
optional = true
version = "0.0.25"

[[order]]

[[order.group]]
id = "org.cloudfoundry.conda"
version = "0.0.17"
