api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "9ebc1e6bb98e07ddec118b9ff85ebe64d2f9a3ae36793eb7966891867a4bc551"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.59.tar.gz"
    source_sha256 = "db35c6e6d4a463bfc621207d09f53c86dc16bc75cedc6ac747c9dc71756ee268"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.59-any-stack-9ebc1e6b.tgz"
    version = "0.0.59"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "e088f7e748857efd0f43386adaca692ad443d39f9bd160eb5c222c9441607924"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.82.tar.gz"
    source_sha256 = "9f5c741d7cc7f857874e83a88d38db85d47f418105a4bd46dc850fde380b27b9"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.82-any-stack-e088f7e7.tgz"
    version = "0.0.82"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "4e8bdaccc646a777468a55924bea7ae05c0efa81bcd9287b8a55fa3247ecfc67"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.66.tar.gz"
    source_sha256 = "9ee1cead4cc32e38a60d65b3aa038d11216abc33b42acebb6e9c159102a97a58"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.66-any-stack-4e8bdacc.tgz"
    version = "0.0.66"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "4ab3ea1a7fde4b4902ca5823c190dc56fdb36b2a1b20f737fb1a94f2ee764d8e"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.85.tar.gz"
    source_sha256 = "f20d41cbfa7512bcaf699240975f3fd4ba9feadf80a6d65193b67439a205ca92"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.85-any-stack-4ab3ea1a.tgz"
    version = "0.0.85"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.85"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.66"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.82"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.59"
