api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "b3581edbdd6adb0b5161ccc57088371cc73de59d9c54036989b34e1273a6e50e"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.52.tar.gz"
    source_sha256 = "19ad3b7a63f5fc60a2babd9784b1d49cff7e1464493370d9d9d111fc1c2c321e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.52-any-stack-b3581edb.tgz"
    version = "0.0.52"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "b5bbd59afd130c4275fde2d04edf2738e9acd1adab0efc1ae573d9b4f6c7f5d3"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.73.tar.gz"
    source_sha256 = "bcfa3f83cc02077c0f644ffae41c5c1950c296766f73d808362f7ab668cbfaa1"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.73-any-stack-b5bbd59a.tgz"
    version = "0.0.73"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "e9ff817149110e3da478a9f8d6ede5b5fdf58a126a0f1dbcc091ea6c557b7a30"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.60.tar.gz"
    source_sha256 = "328f6d3d2bd010b5cc8fc2ebfb3d0945c8badc6c286b361e69dad6b5f6536aa9"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.60-any-stack-e9ff8171.tgz"
    version = "0.0.60"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "498a4a34a90d0a7467cf2e4b845737eb6daa2b00192ae1cd3ec640482d0a321f"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.75.tar.gz"
    source_sha256 = "32e536deb961b7f4d94d64aecb42fdae9053c64a80ddc4a42b6c209a7b91ebe8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.75-any-stack-498a4a34.tgz"
    version = "0.0.75"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.75"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.60"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.73"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.52"
