api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
    source = "https://github.com/buildpack/lifecycle/archive/v0.5.0.tar.gz"
    source_sha256 = "96c50622096b252b596a33731785ae959992078eada660ae068d86607faee6a6"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs2", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.5.0-any-stack-fe375030.tgz"
    version = "0.5.0"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "f745d16a7983c38e569547e7bac2ccb1e6ad3053131328ec80567e651a0feb0c"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.29.tar.gz"
    source_sha256 = "956d8ac0df54b63f0c28fa336b2d95ad1aabb9da7cf871bc27e749aa9cbba8fb"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.29-any-stack-f745d16a.tgz"
    version = "0.0.29"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "b89013cc9a5ff4b73cbcf7e2413f91f69f18e4fc302514dac17fb0bd3522e62b"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.70.tar.gz"
    source_sha256 = "e80d2a332b5baf0e5977b01e267a301128f5e098f47088d057204e2daa300da1"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.70-any-stack-b89013cc.tgz"
    version = "0.0.70"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "05a25d35f806065f9be4a981129e84a88b5f54ef16de8480bf6128a2e0107f6e"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.39.tar.gz"
    source_sha256 = "9520d3000c15496279e5ac1675ebf6f344618506f27d72a9c9e6325ec8adda00"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.39-any-stack-05a25d35.tgz"
    version = "0.0.39"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "156214392834cd5b5abc3158929b6092b7c912eebe4e5e804b4c0fa7dfb5cebb"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.93.tar.gz"
    source_sha256 = "f18d9e62e77033771ceb48314c49bb9ba08d8f1cb0a4772bb4ff68432ea9e910"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.93-any-stack-15621439.tgz"
    version = "0.0.93"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "98f2486dae8c41720ca429adb7af2b8b640019c6d74e0096abf7d18dd5acafb1"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.27.tar.gz"
    source_sha256 = "ebced71d767cbbe4c63f995c849c5e11af456aa877d3389c7407c0bbb40cb8bd"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.27-any-stack-98f2486d.tgz"
    version = "0.0.27"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "09387926bc67e5560738f202ed0c641ae9ef59a22ba88009fee897891095154a"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.77.tar.gz"
    source_sha256 = "7635f9f1b9bf1f23afac3afc0bc2451f593e33d559d31c3e79401bb3755c8a58"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.77-cflinuxfs3-09387926.tgz"
    version = "0.0.77"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "b4e30a5db3f6ecb7aa3eb7c476f9da2e986f1d5e7e5e49a5317705f3de1916ec"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.38.tar.gz"
    source_sha256 = "d9edf43a4e8f1faf1217025689d405a528015f564f02337db40fd8d6408951c7"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.38-any-stack-b4e30a5d.tgz"
    version = "0.0.38"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "07baa3fb0e87dd8953ddd3277906d344d4a8d7e801662a19b122627579540f25"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.97.tar.gz"
    source_sha256 = "86968cbb283dca43bbae3d0f341be02861d78ad7435f7657022afb0f302d48f7"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.97-cflinuxfs3-07baa3fb.tgz"
    version = "0.0.97"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.97"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.77"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.93"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.70"
