api = "0.2"

[buildpack]
  id = "org.cloudfoundry.python"
  name = "Python Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
    source = "https://github.com/buildpack/lifecycle/archive/v0.5.0.tar.gz"
    source_sha256 = "96c50622096b252b596a33731785ae959992078eada660ae068d86607faee6a6"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs2", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.5.0-any-stack-fe375030.tgz"
    version = "0.5.0"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "f745d16a7983c38e569547e7bac2ccb1e6ad3053131328ec80567e651a0feb0c"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.29.tar.gz"
    source_sha256 = "956d8ac0df54b63f0c28fa336b2d95ad1aabb9da7cf871bc27e749aa9cbba8fb"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.29-any-stack-f745d16a.tgz"
    version = "0.0.29"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.conda"
    sha256 = "92a247a0770665e0cc134d138932fbe1e1f9b704d5a3cf72db164f728aae048d"
    source = "https://github.com/cloudfoundry/conda-cnb/archive/v0.0.73.tar.gz"
    source_sha256 = "e7481d73ef85b488e4177109305de69bec8007ea503be7c9e56f71a92127a753"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.conda/org.cloudfoundry.conda-0.0.73-any-stack-92a247a0.tgz"
    version = "0.0.73"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "05a25d35f806065f9be4a981129e84a88b5f54ef16de8480bf6128a2e0107f6e"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.39.tar.gz"
    source_sha256 = "9520d3000c15496279e5ac1675ebf6f344618506f27d72a9c9e6325ec8adda00"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.39-any-stack-05a25d35.tgz"
    version = "0.0.39"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pip"
    sha256 = "08bf21fa01d0bbefb0322cf366b922d97008ea749f329a705ec8ac40dd7ab966"
    source = "https://github.com/cloudfoundry/pip-cnb/archive/v0.0.95.tar.gz"
    source_sha256 = "c33fc5c7b3266337f2b464586a6bc4a2b406d151818159a05931626fe2de1152"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pip/org.cloudfoundry.pip-0.0.95-any-stack-08bf21fa.tgz"
    version = "0.0.95"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "98f2486dae8c41720ca429adb7af2b8b640019c6d74e0096abf7d18dd5acafb1"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.27.tar.gz"
    source_sha256 = "ebced71d767cbbe4c63f995c849c5e11af456aa877d3389c7407c0bbb40cb8bd"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.27-any-stack-98f2486d.tgz"
    version = "0.0.27"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.pipenv"
    sha256 = "15b9781bd50cd48897d27aed45b55b1a4e95968b55eee83838dd594c598e2da6"
    source = "https://github.com/cloudfoundry/pipenv-cnb/archive/v0.0.78.tar.gz"
    source_sha256 = "efa8d766636f42718a13651d3b37949d7a7559dd1fd53be5fa11388383c501f0"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.pipenv/org.cloudfoundry.pipenv-0.0.78-cflinuxfs3-15b9781b.tgz"
    version = "0.0.78"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "b4e30a5db3f6ecb7aa3eb7c476f9da2e986f1d5e7e5e49a5317705f3de1916ec"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.38.tar.gz"
    source_sha256 = "d9edf43a4e8f1faf1217025689d405a528015f564f02337db40fd8d6408951c7"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.38-any-stack-b4e30a5d.tgz"
    version = "0.0.38"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.python-runtime"
    sha256 = "41f12d30e57204926639e7508e3928f1aeb36697f2db77f4f0c30509471e8da9"
    source = "https://github.com/cloudfoundry/python-runtime-cnb/archive/v0.0.98.tar.gz"
    source_sha256 = "809352128b1f714160cee048e5597ebf4a6c4eeafb75a3fdbde0b2a690eff89a"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.python-runtime/org.cloudfoundry.python-runtime-0.0.98-cflinuxfs3-41f12d30.tgz"
    version = "0.0.98"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.python-runtime"
    version = "0.0.98"

  [[order.group]]
    id = "org.cloudfoundry.pipenv"
    version = "0.0.78"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.pip"
    version = "0.0.95"
    optional = true

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.conda"
    version = "0.0.73"
